### PR TITLE
Fixing randomly failing log assertion

### LINKED ISSUE #4387: Acpt test: When_pump_throws_on_stop is flaky
It fails now and then on the build server (see details below)

https://builds.particular.net/viewLog.html?buildId=201639&tab=buildResultsDiv&buildTypeId=NServiceBusCore_Build

<details>
  Expected: String containing "Receiver Main listening to queue PumpThrowsOnStop.EndpointThatThrowsOnPumpStop threw an exception on stopping. System.InvalidOperationException: ExceptionInPumpStop"
  But was:  "Receiver Legacy Retries Processor listening to queue PumpThrowsOnStop.EndpointThatThrowsOnPumpStop.Retries threw an exception on stopping. System.InvalidOperationException: ExceptionInPumpStop
   at NServiceBus.AcceptanceTests.Core.FakeTransport.FakeReceiver.<Stop>d__3.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.AcceptanceTests\Core\FakeTransport\FakeReceiver.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiver.<Stop>d__6.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\TransportReceiver.cs:line 59"

at NServiceBus.AcceptanceTests.Core.Stopping.When_pump_throws_on_stop.<Should_log_exception>d__0.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.AcceptanceTests\Core\Stopping\When_pump_throws_on_stop.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
at NUnit.Framework.Internal.ExceptionHelper.Rethrow(Exception exception)
at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)

------- Stdout: -------
MsmqTransport - Started @ 12/12/2016 13:18:24
Stopping endpoint: PumpThrowsOnStop.EndpointThatThrowsOnPumpStop
Endpoint: PumpThrowsOnStop.EndpointThatThrowsOnPumpStop stopped (00:00:00.0041140s)
MsmqTransport - Finished @ 12/12/2016 13:18:24
------------------------------------------------------
Test summary for: MsmqTransport

Using settings:
   Transport.ConnectionString: cacheSendConnection=false;journal=false;
   Persistence: NServiceBus.InMemoryPersistence
   ConfigureTestExecution.PumpThrowsOnStop.EndpointThatThrowsOnPumpStop: ConfigureEndpointMsmqTransport; ConfigureEndpointInMemoryPersistence
   Transport: NServiceBus.MsmqTransport

Endpoints:
     - PumpThrowsOnStop.EndpointThatThrowsOnPumpStop
Result: Successful - Duration: 00:00:00.0701836

Context:
TestRunId = 5bb19c69-6b79-4d95-9dc3-9ea6f9613c88
EndpointsStarted = True
HasNativePubSubSupport = False

Trace:

------------------------------------------------------
Total time for testrun: 00:00:00.0702938
</details>

### PR DESCRIPTION
**Pull request by timbussmann**
Fixes #4387 
The assertion could randomly fail because the the pump for the legacy retries satellite will fail additionally to the main pump. This causes multiple log entries matching the LINQ filter in the result where it can switch randomly between the main and the legacy retries satellite to be the first.

Switched the log filter to be more specific on the log filter to avoid this race condition.

An alternative would be to disable the legacy retries satellite for this test but then any other satellite receiver could introduce the same race condition again.

### CODE REVIEW

File: src/NServiceBus.AcceptanceTests/Core/Stopping/When_pump_throws_on_stop.cs [hunk 1]
```diff
@@ -12,16 +12,16 @@ namespace NServiceBus.AcceptanceTests.Core.Stopping
...
         {
             var context = await Scenario.Define<ScenarioContext>()
                 .WithEndpoint<EndpointThatThrowsOnPumpStop>()
                 .Done(c => c.EndpointsStarted)
                 .Run();
 
-            var logItem = context.Logs.FirstOrDefault(item => item.Message.Contains("Receiver") && item.Level == LogLevel.Warn);
-            Assert.IsNotNull(logItem);
-            StringAssert.Contains("Receiver Main listening to queue PumpThrowsOnStop.EndpointThatThrowsOnPumpStop threw an exception on stopping. System.InvalidOperationException: ExceptionInPumpStop", logItem.Message);
+            Assert.IsNotNull(context.Logs.Single(l =>
```
Comment (danielmarbach) [inline src/NServiceBus.AcceptanceTests/Core/Stopping/When_pump_throws_on_stop.cs]: Should that be `SingleOrDefault` if you use `Assert.IsNotNull`?

Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/Core/Stopping/When_pump_throws_on_stop.cs]: yeah makes sense 👍

**Comment by timbussmann** [comment]
addressed your comment @danielmarbach

**Comment by danielmarbach** [comment]
Small enough so I merged
