### PR TITLE
Do not autosubscribe unless there is routing info when using unicast transports

### LINKED ISSUE #3596: Autosubscribe for unicast should require explicit mappings
In V5 we used to require routing information to be present when autosubscribing on unicast transports. It has changed since then. I did some archaeology and found [this](https://github.com/Particular/NServiceBus/commit/290f24c49042e73ae8fd7d3243aee2ccd028b03d) commit by @andreasohlund and [that](https://github.com/Particular/NServiceBus/commit/66d91e7a6a439717b1ae7856f81594704616dc6f) one by myself and @dvdstelt .

It seems like the three of us removed that flag and changed the behavior to not check the routing. This results in an exception being thrown when there is a handler for event `E` but there is no information on who publishes `E`. Is this the behavior we want to continue having in V6 or should we revert back to old V5 behavior?

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Fixes #3596

Also fixes the behavior of AT framework when one of the endpoints fail to start (adding a missing `await`)

### CODE REVIEW

File: src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs [hunk 1]
```diff
@@ -265,6 +265,7 @@ static string GenerateTestTimedOutMessage(TimeSpan maxTime)
             {
                 throw new Exception("Starting endpoints took longer than 2 minutes");
             }
+            await completedTask.ConfigureAwait(false);
```
Comment (andreasohlund) [inline src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs]: How could we have missed this in the past? (how did you find this?)

File: src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs [hunk 2]
```diff
@@ -56,20 +59,28 @@ static List<Type> GetMessageTypesHandledByThisEndpoint(MessageHandlerRegistry ha
...
+                    if (predicate(eventType))
                     {
-                        await session.Subscribe(eventType).ConfigureAwait(false);
-                        Logger.DebugFormat("Auto subscribed to event {0}", eventType);
+                        try
+                        {
+                            await session.Subscribe(eventType).ConfigureAwait(false);
+                            Logger.DebugFormat("Auto subscribed to event {0}", eventType);
+                        }
+                        catch (Exception ex)
```
Comment (andreasohlund) [inline src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs]: Why the try catch?

File: src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs [hunk 3]
```diff
@@ -56,20 +59,28 @@ static List<Type> GetMessageTypesHandledByThisEndpoint(MessageHandlerRegistry ha
...
+                        {
+                            throw new Exception("s", ex);
```
Comment (andreasohlund) [inline src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs]: "s" ??

File: src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs (hunk 1 above)
Comment (danielmarbach) [inline src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs]: What is the intention of this change?

`Task.WhenAll` returns `Task<Task>` so the result of the task created by `Task.WhenAll` is the first already completed Task. 

Is your intention to rethrow any exceptions that might have happened in the `whenAll`?

Comment (SzymonPobiega) [inline src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs]: @danielmarbach yes. Without it, any exception that happens when the endpoints starts is swallowed (logged to the console but the test turns out green)

File: src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs (hunk 3 above)
Comment (SzymonPobiega) [inline src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs]: I was testing if I really get an exception here before I realized it is getting swallowed by the testing framework. Forgot to remove this code. Corrected now.

File: src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs (hunk 1 above)
Comment (danielmarbach) [inline src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs]: Ok then

Comment (SzymonPobiega) [inline src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs]: @danielmarbach I already blame you for all the async stuff. My understanding of this code is that we capture the faulted task in `completedTask` variable but since `WhenAny` returns `Task<Task>`, we were not awaiting the `completedTask` because `StartEndpoints` returns a brand new task, not `completedTask`.

Comment (danielmarbach) [inline src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs]: Not exactly. I can explain in more detail on a call if you are curious

**Comment by SzymonPobiega** [comment]
I think this is ready to go

File: src/NServiceBus.Msmq.AcceptanceTests/When_Audit_OverrideTimeToBeReceived_set_and_native_receive_tx.cs [hunk 4]
```diff
@@ -12,12 +11,17 @@ public class When_Audit_OverrideTimeToBeReceived_set_and_native_receive_tx : NSe
         [Test]
         public async Task Endpoint_should_not_start_and_show_error()
         {
-            var context = await Scenario.Define<Context>()
-                .WithEndpoint<Endpoint>()
-                .Done(c => c.EndpointsStarted)
-                .Run();
-
-            Assert.True(context.Exceptions.First().Message.Contains("Setting a custom OverrideTimeToBeReceived for audits is not supported on transactional MSMQ."));
+            try
```
Comment (andreasohlund) [inline src/NServiceBus.Msmq.AcceptanceTests/When_Audit_OverrideTimeToBeReceived_set_and_native_receive_tx.cs]: This is because `Assert.Throws` don't play ball with async in the nunit version we use right?

Comment (timbussmann) [inline src/NServiceBus.Msmq.AcceptanceTests/When_Audit_OverrideTimeToBeReceived_set_and_native_receive_tx.cs]: I think you can use Assert.Throws(async () => await...)

Comment (danielmarbach) [inline src/NServiceBus.Msmq.AcceptanceTests/When_Audit_OverrideTimeToBeReceived_set_and_native_receive_tx.cs]: Better to use Assert.That(async () => , Throws....)

Comment (danielmarbach) [inline src/NServiceBus.Msmq.AcceptanceTests/When_Audit_OverrideTimeToBeReceived_set_and_native_receive_tx.cs]: See https://github.com/Particular/NServiceBus/pull/3405/files

File: src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs [hunk 5]
```diff
@@ -31,14 +33,15 @@ protected internal override void Setup(FeatureConfigurationContext context)
...
+            var publishers = context.Settings.Get<Publishers>();
 
             context.RegisterStartupTask(b =>
             {
                 var handlerRegistry = b.Build<MessageHandlerRegistry>();
-
                 var messageTypesHandled = GetMessageTypesHandledByThisEndpoint(handlerRegistry, conventions, settings);
-
-                return new ApplySubscriptions(messageTypesHandled, type => TaskEx.TrueTask);
+                return new ApplySubscriptions(messageTypesHandled, eventType => !requireExplicitRouting || publishers.GetPublisherFor(eventType).Any());
```
Comment (timbussmann) [inline src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs]: couldn't we apply the predicate just here and simplify `ApplySubscriptions` a lot?

File: src/NServiceBus.AcceptanceTests/Routing/When_handler_exists_but_routing_information_is_missing.cs [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+                    return Task.FromResult(0);
+                }
+            }
+        }
+
+        public class MyEvent : IEvent
+        {
+        }
+    }
+}
```
Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/Routing/When_handler_exists_but_routing_information_is_missing.cs]: I assume the test failed before because the endpoint couldn't start up at all? The test isn't too easy to understand at first glance since you have to know that autosubscribe will throw an exception in case the information is missing.

can we rename the test + assertion or at least add a comment?

maybe `when_using_autosubscribe_with_missing_routing_information` `Should_not_throw_on_endpoint_startup`?

Comment (SzymonPobiega) [inline src/NServiceBus.AcceptanceTests/Routing/When_handler_exists_but_routing_information_is_missing.cs]: Fixed.

File: src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs (hunk 5 above)
Comment (SzymonPobiega) [inline src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs]: Fixed.

**Comment by SzymonPobiega** [comment]
@andreasohlund @timbussmann applied Tim's comments, rebased and squashed.

**Comment by andreasohlund** [comment]
Will merge once the build is completed
