### PR TITLE
SLR and Faults should not commit transactions

### LINKED ISSUE #3032: SLR/Moving to error does not handle outgoing messages properly in v6
taskforce: @MarcinHoppe  @weralabaj @mikeminutillo

Chicken: @tmasternak

# Problem

The goal of this task is to fix two issues identified in Recoverability features in current development version of v6.
* Incorrect logic for moving message to timeouts or error queues. Currently SLR and Faults reuse the receive transaction on the transport level to move messages to timeouts and errors. This transaction gets committed which may (and usually will) result in side-effects of message processing being committed as well e.g. any messages which where produced by handler.
* Current implementation of FLR errors (stored in memory structure which is cleaned as a whole each 5 min) may result in consistently failing message being processed infinitely many times. For example in side-by-side deployment when two instances of endpoint consume message from the same queue. In such case it is possible that instance A will do message processing until it fails and store FLR counter for it in memory. The message will be picked up by instance B which will behave in the same way but before it returns message to queue instance A FLR error data will already be cleared. In fact that will happen also for single instance if rolling back the transaction will take more than 5 min.

# Redesign approach 
The first problem can be solved by the approach taken in v5 i.e. SLR and Faults handling will happen as soon as message reaches SLR or Faults behaviors and will be executed if FLR error counter has reached maximum for SLR to be executed or SLR counter (stored in message header) has reached maximum for Faults logic to be executed.
The second problem will be solved by implementing LRU cache for FLR errors with relatively big constraint on elements count (e.g. 1000). In such case we will prevent any memory leaks from happening and we will minimize the possibility of infinite message processing (for FLR message counter to be cleared 1000 other unique failing messages would have to be observed before reaching maximum FLR retires for the original one). The size of LRU cache should take into consideration the size of the exception object which is stored for each failing message.
Recoverability implementation should not be reused for satellites as their requirements are usually different. In addition for satellites some recoverability features should not be enabled and design should prevent from accidentally turning them on e.g. SLR for .Timeouts. 

# Impact
Taking into consideration first issues described in the *Problem* section the impact is large.

# Plan of Attack
 - [x] Changes in `Core` [PR](https://github.com/Particular/NServiceBus/pull/3614)
   - [x] Change SLR and Faults behavior to match v5
   - [x] Unit tests for transport transaction modes other than `None`: behaviors have to be invoked twice (@tmasternak)
   - [x] Merge FLR failure storage with SLR/MoveToErrorQueue failure storage (@weralabaj)
     - [x]  Separate TimeoutManager storage (@weralabaj)
     - [x] Make LRU cache size configurable (@weralabaj)
   - [x] Make sure exception is properly captured before adding to message headers (@MarcinHoppe)
   - [x] Make FLRetries header available for custom SLR policies (@MarcinHoppe)
   - [x] Turn off SLR for transaction mode `None` (@tmasternak)
   - [x] Internal TF Review
 - [x] Replace acceptance tests that cover this bug to component level tests [PR](https://github.com/Particular/NServiceBus/pull/3664)
 - [x] Maintainer group Review
 - [x] Handle large error headers
  - [x] Create `Consider for V6 Launch` issue in PlatDev and link to here and this [bug](https://github.com/Particular/NServiceBus/issues/3023). [Issue](https://github.com/Particular/PlatformDevelopment/issues/699) has been created
 - [x] Documentation (@tmasternak)
  - [x] Review v5 doco wrt FLR/SLR when transactions are turned off. [PR](https://github.com/Particular/docs.particular.net/pull/1365)
- [x] Update doco - not throwing exception (@weralabaj) https://github.com/Particular/docs.particular.net/commit/1b2c815746f27691315803fcfec808cdda8d8d89
 - [x] Investigate failing RabbitMQ ATTs

# Downstream repos:  
 - [x] TimeoutManager [PR](https://github.com/Particular/NServiceBus/pull/3337)
 - [ ] ~~Gateway [issue](https://github.com/Particular/NServiceBus.Gateway/issues/41)(Out of scope for this work)~~

### PR DESCRIPTION
**Pull request by MarcinHoppe**
Resolves #3032. The idea is to properly implement changes started in #3031.

### CODE REVIEW

**Comment by MarcinHoppe** [comment]
@tmasternak @weralabaj @andreasohlund @timbussmann This is the WIP branch that I mentioned in the meeting today. Please take a look if these tests make sense, this will take the issue forward.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_deferring_message_during_slr.cs [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+                public Task Handle(MessageToFail message, IMessageHandlerContext context)
+                {
+                    if (message.Id == TestContext.Id)
+                    {
+                        TestContext.NumberOfProcessingAttempts++;
+
+                        Transaction.Current.TransactionCompleted += CaptureTransactionStatus;
+                    }
+
+                    throw new SimulatedException();
```
Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_deferring_message_during_slr.cs]: I think you can move that inside the if statement. Then you can remove `DoNotFailOnErrorMessages()` and just assert that the message was moved to the error queue instead of having an error spy endpoint?

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_deferring_message_during_slr.cs [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+    using System.Threading.Tasks;
+    using System.Transactions;
+    using AcceptanceTesting;
+    using EndpointTemplates;
+    using Features;
+    using NServiceBus.Config;
+    using NUnit.Framework;
+    using ScenarioDescriptors;
+
+    public class When_deferring_message_during_slr : NServiceBusAcceptanceTest
```
Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_deferring_message_during_slr.cs]: how about "when_message_is_handled_by_slr"?

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_goes_through_all_retries.cs [hunk 3]
```diff
@@ -0,0 +1,176 @@
...
+                .WithEndpoint<ErrorSpy>()
+                .Done(c => c.MessageMovedToErrorQueue)
+                .Repeat(r => r.For<AllNativeMultiQueueTransactionTransports>())
+                .Should(c => Assert.IsFalse(c.OutgoingMessageReceived, "Outgoing message was unexpectedly dispatched"))
+                .Should(c => Assert.AreEqual(4, c.NumberOfProcessingAttempts))
+                .Run();
+        }
+
+        [Test]
+        public async Task Should_not_send_outgoing_messages_using_immediate_dispatch()
```
Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_goes_through_all_retries.cs]: sends using immediate dispatch should not enlist in an existing transaction. These assertions look wrong to me.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_deferring_message_during_slr.cs [hunk 4]
```diff
@@ -0,0 +1,112 @@
...
+    {
+        [Test]
+        public async Task Should_not_commit_transaction()
```
Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_deferring_message_during_slr.cs]: may use `Should_not_commit_distributed_transaction`

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_goes_through_all_retries.cs [hunk 5]
```diff
@@ -0,0 +1,176 @@
...
+    using System.Threading.Tasks;
+    using AcceptanceTesting;
+    using EndpointTemplates;
+    using Features;
+    using NServiceBus.Config;
+    using NServiceBus.Pipeline;
+    using NUnit.Framework;
+    using ScenarioDescriptors;
+
+    public class When_message_goes_through_all_retries : NServiceBusAcceptanceTest
```
Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_goes_through_all_retries.cs]: what role do retries play in this test? This seems to test transaction handling?

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_goes_through_all_retries.cs [hunk 6]
```diff
@@ -0,0 +1,176 @@
...
+    {
+        [Test]
+        public async Task Should_not_send_outgoing_messages_using_batched_dispatch()
```
Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_goes_through_all_retries.cs]: for batched dispatch with multi-queue transactions, it would actually make sense to throw an exception in the `ITransportReceiveContext` stage, because that's where batched messages have been sent.

It seems like we'd rather have tests using single-queue transactions to verify that we "rollback" outgoing messages on exceptions before the `ITransportReceiveContext` stage (and dispatch them afterwards).

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_goes_through_all_retries.cs [hunk 7]
```diff
@@ -0,0 +1,176 @@
...
+        class Endpoint : EndpointConfigurationBuilder
+        {
+            public Endpoint()
+            {
+                EndpointSetup<DefaultServer>((config, context) =>
+                {
+                    config.DisableFeature<FirstLevelRetries>();
+                    config.EnableFeature<SecondLevelRetries>();
+                    config.EnableFeature<TimeoutManager>();
+                    config.Pipeline.Register(new RegisterThrowingBehavior("SecondLevelRetries"));
```
Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_goes_through_all_retries.cs]: this may register the behavior before or after the error queue behavior

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_deferring_message_during_slr.cs (hunk 1 above)
Comment (MarcinHoppe) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_deferring_message_during_slr.cs]: How do I assert that message was moved to the error queue without the error spy endpoint picking it up?

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_goes_through_all_retries.cs (hunk 5 above)
Comment (MarcinHoppe) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_goes_through_all_retries.cs]: The point is to test if moving the message to error queue or deferring it by SLR does not accidentally cause outgoing messages to be sent. So these tests verify if retries don't have unexpected effects on transactions handling.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_goes_through_all_retries.cs (hunk 7 above)
Comment (MarcinHoppe) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_goes_through_all_retries.cs]: Move to error queue is insrted before SLR. Throwing behavior is inserted after SLR. Doesn't this determine position of the throwing behavior in the pipeline? If the debugger doesn't lie to me, the sequence is:

Error queue -> SLR -> throwing behavior -> handler

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_deferring_message_during_slr.cs (hunk 2 above)
Comment (MarcinHoppe) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_deferring_message_during_slr.cs]: Makes sense. Renamed.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_goes_through_all_retries.cs (hunk 3 above)
Comment (MarcinHoppe) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_goes_through_all_retries.cs]: You're absolutely right, great catch. I updated the test.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_deferring_message_during_slr.cs (hunk 4 above)
Comment (MarcinHoppe) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_deferring_message_during_slr.cs]: Makes sense. Renamed.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_goes_through_all_retries.cs (hunk 7 above)
Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_goes_through_all_retries.cs]: yes you're right since you're using InsertAfter. Mixed it up with InsertBefore. Not a big fan of the parameter though.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_goes_through_all_retries.cs (hunk 5 above)
Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_goes_through_all_retries.cs]: I think we can separate the concerns the following way:

Retry & Error Queue features:
* When FLR handles message: verify message processing is aborted and message is retried immediately
* When SLR handles message: verify message processing is aborted and message is retried with delay
* When ErrorQ behavior handled message: verify message processing is aborted and message is sent to errorqueue

"Batching feature":
* When message processing is aborted: verify that no outgoing message is dispatched (besides immediate dispatches)

Transactions:
* When message processing fails & transactions enabled (>= single queue): verify incoming message is rolled back. Dispatched messages are not rolled back
* When message processing fails & transactions enabled (>= multi queue): verify incoming message and dispatched messages are rolled back.
* When message processing fails & transactions disabled: verify incoming/dispatched message are not rolled back.

so that's why why I think we should scope our expectations to a specific behavior/feature and not a combination of features & configurations. Does that make sense somehow? (Note: I just dumped some thoughts on this list, this may be wrong or not behave like it's described on different transports)

**Comment by tmasternak** [comment]
I think we should test 2 scenarios:
 * SLR fires and there are messages generated by handler
 * Errors fire and there are messages generated by handler

We should add a permutation over `TransactionModes` over that.

I think that the tests currently have too big of a scope:
 * We should not be testing behavior of immediate dispatch here. If we feel we should let's add that but in different PR and not in recoverability tests
 * The fact that we need to fail after batching is done is test implementation detail. Once more we are not testing batching here
 * We should not care how many times SLR or FLR fires

**Comment by timbussmann** [comment]
> I think that the tests currently have too big of a scope

I agree. As i tried to describe inhttps://github.com/Particular/NServiceBus/pull/3614#discussion_r57130038 we're mixing up different features. (FLR, SLR, Batched Dispatch and Transactions)

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_handled_by_slr.cs [hunk 8]
```diff
@@ -0,0 +1,165 @@
...
+                        .Transactions(testContext.TransactionMode);
+                    config.DisableFeature<FirstLevelRetries>();
+                    config.EnableFeature<SecondLevelRetries>();
+                    config.EnableFeature<TimeoutManager>();
+                    config.Pipeline.Register(new RegisterThrowingBehavior());
+                    config.SendFailedMessagesTo(ErrorQueueName);
+                })
+                    .WithConfig<SecondLevelRetriesConfig>(slrConfig =>
+                    {
+                        slrConfig.NumberOfRetries = 3;
```
Comment (tmasternak) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_handled_by_slr.cs]: Shouldn't it be enought to do 1 retry?

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_handled_by_slr.cs [hunk 9]
```diff
@@ -0,0 +1,165 @@
...
+            })
+            .WithEndpoint<Endpoint>(b => b.DoNotFailOnErrorMessages()
+                .When((session, context) => session.SendLocal(new InitiatingMessage
+                {
+                    Id = context.Id
+                }))
+            )
+            .WithEndpoint<ReceiverEndpoint>()
+            .WithEndpoint<ErrorSpy>()
+            .Done(c => c.MessageMovedToErrorQueue)
```
Comment (tmasternak) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_handled_by_slr.cs]: I think that we need to merge the Receiver and ErrorSpy and set ErrorSpy concurrency limit to 1. Otherwise it is possible that message will be moved to error queue and processed before the receiver gets it.

**Comment by tmasternak** [comment]
@MarcinHoppe tests look good :+1:

File: src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ProcessingFailureInfo.cs [hunk 10]
```diff
@@ -4,15 +4,20 @@
 
     class ProcessingFailureInfo
     {
-        public ProcessingFailureInfo(int numberOfFailedAttempts, Exception exception)
+        public ProcessingFailureInfo(int numberOfFailedAttempts, Exception exception, bool shouldMoveToErrorQueue = false, bool shouldDeferForRetry = false)
```
Comment (tmasternak) [inline src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ProcessingFailureInfo.cs]: For now we are using separate `FailureStorage` instances so we could have only single flag. Something like `HandleOnNextProcessing'.

File: src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueNoTransactionBehavior.cs [hunk 11]
```diff
@@ -0,0 +1,72 @@
...
+
+        public override async Task Invoke(ITransportReceiveContext context, Func<Task> next, Func<IFaultContext, Task> fork)
+        {
+            try
+            {
+                await next().ConfigureAwait(false);
+            }
+            catch (Exception exception)
+            {
+                try
```
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueNoTransactionBehavior.cs]: If we extracted `MoveToErrorQueueMethod` maybe we could merge transactional and nontransactional behavior and just pass `TransportTransactionMode` as one of the parameters.

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs [hunk 12]
```diff
@@ -11,37 +11,31 @@ namespace NServiceBus
...
-            {
-                context.Message.Headers.Remove(Headers.Retries);
-                throw; // no SLR for poison messages
-            }
-            catch (Exception ex)
+            var failureInfo = failureInfoStorage.GetFailureInfoForMessage(context.Message.MessageId);
+
+            if (failureInfo.ShouldDeferForRetry)
             {
                 var message = context.Message;
```
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: The same as https://github.com/Particular/NServiceBus/pull/3614/files#r57437581

File: src/NServiceBus.Core/DelayedDelivery/TimeoutManager/FailureInfoStorage.cs [hunk 13]
```diff
@@ -13,7 +13,7 @@ public FailureInfoStorage(int maxElements = 1000)
             this.maxElements = maxElements;
         }
 
-        public void RecordFailureInfoForMessage(string messageId, Exception exception)
+        public void RecordFailureInfoForMessage(string messageId, Exception exception, bool shouldMoveToErrorQueue = false, bool shouldDeferForRetry = false)
```
Comment (tmasternak) [inline src/NServiceBus.Core/DelayedDelivery/TimeoutManager/FailureInfoStorage.cs]: Instead of adding flags in signature can we have separate methods that `SLR` and `Errors` would use? For example `MarkForSLRDeferral` and `MarkForMovingToErrorQueue`.

File: src/NServiceBus.Core.Tests/Faults/MoveFaultsToErrorQueueTests.cs [hunk 14]
```diff
@@ -12,89 +12,145 @@ namespace NServiceBus.Core.Tests
...
+            {
+                await behavior.Invoke(context, () => Task.FromResult(0));
+            }
 
-            Assert.AreEqual("someid", fakeFaultPipeline.MessageSent.MessageId);
+            Assert.AreEqual("errors-queue", faultPipeline.Destination);
+            Assert.AreEqual("message-id", faultPipeline.MessageSent.MessageId);
         }
 
         [Test]
```
Comment (MarcinHoppe) [inline src/NServiceBus.Core.Tests/Faults/MoveFaultsToErrorQueueTests.cs]: This is redundant. `[TestCase]` is enough for NUnit to run this as a test method.

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetries.cs [hunk 15]
```diff
@@ -29,9 +40,10 @@ protected internal override void Setup(FeatureConfigurationContext context)
             var retryPolicy = GetRetryPolicy(context.Settings);
 
             context.Container.RegisterSingleton(typeof(SecondLevelRetryPolicy), retryPolicy);
+
             context.Pipeline.Register<SecondLevelRetriesBehavior.Registration>();
 
-            context.Container.ConfigureComponent(b => new SecondLevelRetriesBehavior(retryPolicy, context.Settings.LocalAddress()), DependencyLifecycle.InstancePerCall);
+            context.Container.ConfigureComponent(b => new SecondLevelRetriesBehavior(retryPolicy, context.Settings.LocalAddress(), b.Build<FailureInfoStorage>()), DependencyLifecycle.InstancePerCall);
```
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetries.cs]: I think that we should create the `FailureStorageInfo` by hand. We want to get rid of builder and currently we depend on `MoveFaultsToErrorQueue` behavior to create it.

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs [hunk 16]
```diff
@@ -30,39 +43,51 @@ public SecondLevelRetriesBehavior(SecondLevelRetryPolicy retryPolicy, string loc
             }
             catch (Exception ex)
             {
-                var message = context.Message;
-                var currentRetry = GetNumberOfRetries(message.Headers) + 1;
+                failureInfoStorage.MarkForDeferralForSecondLevelRetry(context.Message.MessageId, ExceptionDispatchInfo.Capture(ex));
```
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: Currently when exception is thrown and `SLR` has reached it's limit we still rollback the message and throw in `DeferMessageForSecondLevelRetry` on next receive. We could bubble the exception here but would need to check the policy as well.

File: src/NServiceBus.Core/Recoverability/Faults/StoreFaultsInErrorQueue.cs [hunk 17]
```diff
@@ -18,7 +19,12 @@ protected internal override void Setup(FeatureConfigurationContext context)
         {
             var errorQueue = ErrorQueueSettings.GetConfiguredErrorQueue(context.Settings);
             context.Settings.Get<QueueBindings>().BindSending(errorQueue);
-            context.Pipeline.Register(new MoveFaultsToErrorQueueBehavior.Registration(errorQueue, context.Settings.LocalAddress()));
+
+            var failureInfoStorage = new FailureInfoStorage(context.Settings.GetOrDefault<int?>("Recoverability.FailureInfoStorage.CacheSize") ?? 1000);
+            context.Container.RegisterSingleton(failureInfoStorage);
```
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/Faults/StoreFaultsInErrorQueue.cs]: I think that we agreed to not share the store between behaviors.

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs [hunk 18]
```diff
@@ -30,39 +43,51 @@ public SecondLevelRetriesBehavior(SecondLevelRetryPolicy retryPolicy, string loc
...
-                    message.RevertToOriginalBodyIfNeeded();
-                    var messageToRetry = new OutgoingMessage(message.MessageId, message.Headers, message.Body);
+        async Task DeferMessageForSecondLevelRetry(ITransportReceiveContext context, Func<IRoutingContext, Task> fork, IncomingMessage message, ProcessingFailureInfo failureInfo)
+        {
+            var currentRetry = GetNumberOfRetries(message.Headers) + 1;
 
-                    messageToRetry.Headers[Headers.Retries] = currentRetry.ToString();
-                    messageToRetry.Headers[RetriesTimestamp] = DateTimeExtensions.ToWireFormattedString(DateTime.UtcNow);
+            var numberOfFirstLevelRetries = failureInfo.NumberOfFailedFlrAttempts - 1;
+            message.Headers[Headers.FLRetries] = numberOfFirstLevelRetries.ToString();
```
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: Can we add comment that we are setting this header just because `RetryPolicy` should be able to get it?

File: src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs [hunk 19]
```diff
@@ -8,60 +9,95 @@ namespace NServiceBus
...
         string errorQueueAddress;
+        FailureInfoStorage failureInfoStorage;
         string localAddress;
+        TransportTransactionMode transportTransactionMode;
         static ILog Logger = LogManager.GetLogger<MoveFaultsToErrorQueueBehavior>();
 
         public class Registration : RegisterStep
         {
-            public Registration(string errorQueueAddress, string localAddress)
+            public Registration(string errorQueueAddress, string localAddress, TransportTransactionMode transportTransactionMode)
```
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs]: Can we register this the same way `SecondLevelRetries` is registered. We will avoid one `Builder` call for `FailureStorageInfo`.

File: src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetries.cs [hunk 20]
```diff
@@ -31,13 +28,8 @@ protected internal override void Setup(FeatureConfigurationContext context)
...
             context.Container.RegisterSingleton(retryPolicy);
-
-            var flrStatusStorage = new FlrStatusStorage();
-            context.Container.RegisterSingleton(flrStatusStorage);
-
-            context.RegisterStartupTask(new FlrStatusStorageCleaner(flrStatusStorage));
-
-            context.Pipeline.Register("FirstLevelRetries", b => new FirstLevelRetriesBehavior(b.Build<FlrStatusStorage>(), b.Build<FirstLevelRetryPolicy>()), "Performs first level retries");
+            
+            context.Pipeline.Register("FirstLevelRetries", b => new FirstLevelRetriesBehavior(b.Build<FailureInfoStorage>(), b.Build<FirstLevelRetryPolicy>()), "Performs first level retries");
```
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetries.cs]: Can we pass `FailureInfoStorage` and policy as instance references here?

File: src/NServiceBus.Core/Recoverability/FailureInfoStorage.cs [hunk 21]
```diff
@@ -0,0 +1,122 @@
+namespace NServiceBus
+{
+    using System.Collections.Generic;
+    using System.Runtime.ExceptionServices;
+    using JetBrains.Annotations;
+
+    // The data structure has fixed maximum size. When the data structure reaches its maximum size,
+    // the least recently used (LRU) message processing failure is removed from the storage.
+    class FailureInfoStorage
```
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/FailureInfoStorage.cs]: If we don't want to share this between `FLR`, `SLR` and `Errors` can we make this generic? `SLR` and `Errors` would use `FailureInfoStorage.Of(ExceptionDispatchInfo)` and `FLR` `FailureInfoStorage.Of(Tuple.Of(ExceptionDispatchInfo, int)).

File: src/NServiceBus.Core/Recoverability/FailureInfoStorage.cs [hunk 22]
```diff
@@ -0,0 +1,122 @@
...
+                }
+            }
+        }
+
+        static int NumberOfFailedFlrAttempts(bool shouldMoveToErrorQueue, bool shouldDeferForSecondLevelRetry, FailureInfoNode node)
+        {
+            var isFlrAttemptFailure = !shouldMoveToErrorQueue && !shouldDeferForSecondLevelRetry;
+            if (isFlrAttemptFailure)
+            {
+                return node.FailureInfo.NumberOfFailedFlrAttempts + 1;
```
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/FailureInfoStorage.cs]: FLR counter should not be increased by one by the storage. The value should be passed from the behavior which encapsulates the logic for changing that value.

File: src/NServiceBus.Core/Recoverability/FailureInfoStorage.cs [hunk 23]
```diff
@@ -0,0 +1,122 @@
...
+
+                    failureInfoPerMessage[messageId] = newNode;
+
+                    // Maintain invariant: leastRecentlyUsedMessages.First contains the LRU item.
+                    leastRecentlyUsedMessages.AddLast(newNode.LeastRecentlyUsedEntry);
+                }
+            }
+        }
+
+        static int NumberOfFailedFlrAttempts(bool shouldMoveToErrorQueue, bool shouldDeferForSecondLevelRetry, FailureInfoNode node)
```
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/FailureInfoStorage.cs]: This method is too complex. I think it shows that we should go with generic storage.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_handled_by_slr.cs [hunk 24]
```diff
@@ -0,0 +1,146 @@
...
+    using System.Threading.Tasks;
+    using AcceptanceTesting;
+    using EndpointTemplates;
+    using Features;
+    using NServiceBus.Config;
+    using NServiceBus.Pipeline;
+    using NUnit.Framework;
+    using ScenarioDescriptors;
+
+    public class When_message_is_handled_by_slr : NServiceBusAcceptanceTest
```
Comment (tmasternak) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_handled_by_slr.cs]: Maybe `When_message_is_deferred_by_slr`?

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_handled_by_slr.cs [hunk 25]
```diff
@@ -0,0 +1,146 @@
...
+    {
+        [TestCase(TransportTransactionMode.ReceiveOnly)]
+        [TestCase(TransportTransactionMode.SendsAtomicWithReceive)]
+        [TestCase(TransportTransactionMode.TransactionScope)]
+        public async Task Should_not_send_outgoing_messages_with_transport_transactions(TransportTransactionMode transactionMode)
```
Comment (tmasternak) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_handled_by_slr.cs]: Remove `_transport_transactions`.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue.cs [hunk 26]
```diff
@@ -0,0 +1,168 @@
...
+    using NServiceBus.Pipeline;
+    using NUnit.Framework;
+    using ScenarioDescriptors;
+
+    public class When_message_is_moved_to_error_queue : NServiceBusAcceptanceTest
+    {
+        [TestCase(TransportTransactionMode.ReceiveOnly)]
+        [TestCase(TransportTransactionMode.SendsAtomicWithReceive)]
+        [TestCase(TransportTransactionMode.TransactionScope)]
+        public async Task Should_not_send_outgoing_messages_with_transport_transactions(TransportTransactionMode transactionMode)
```
Comment (tmasternak) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue.cs]: Remove `_transport_transaction`

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs (hunk 18 above)
Comment (andreasohlund) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: Pretty sure the header is a left over from v5 (where headers was the way we communicated with downstream components). I'd say we :fire: it

File: src/NServiceBus.Core/Recoverability/Faults/StoreFaultsInErrorQueue.cs (hunk 17 above)
Comment (weralabaj) [inline src/NServiceBus.Core/Recoverability/Faults/StoreFaultsInErrorQueue.cs]: Don't we have a "Merge FLR failure storage with SLR/MoveToErrorQueue failure storage" on our PoA?

File: src/NServiceBus.Core/Recoverability/FailureInfoStorage.cs (hunk 21 above)
Comment (weralabaj) [inline src/NServiceBus.Core/Recoverability/FailureInfoStorage.cs]: My understanding is that we DO want to share it.

File: src/NServiceBus.Core/Recoverability/FailureInfoStorage.cs (hunk 23 above)
Comment (weralabaj) [inline src/NServiceBus.Core/Recoverability/FailureInfoStorage.cs]: @MarcinHoppe Would splitting this method cause as consistency grief for the storage?

File: src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs (hunk 19 above)
Comment (weralabaj) [inline src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs]: > Can we register this the same way SecondLevelRetries is registered.

It's a feature, so isn't it a bit different? I'm not sure what you had in mind exactly, registered where?

**Comment by weralabaj** [comment]
@Particular/nservicebus-maintainers Given that Marcin is off today and Tomasz apparently should be moved out of the TF, I think it'd make sense to get your input today.

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetries.cs (hunk 15 above)
Comment (MarcinHoppe) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetries.cs]: We want all behaviors to share the instance of `FailureInfoStorage`. `MoveFaultsToErrorQueue` is the only behavior here that cannot be disabled by the user so it makes sense for it to create this instance.

File: src/NServiceBus.Core/Recoverability/Faults/StoreFaultsInErrorQueue.cs (hunk 17 above)
Comment (MarcinHoppe) [inline src/NServiceBus.Core/Recoverability/Faults/StoreFaultsInErrorQueue.cs]: We need to share the store among all behaviors to be able to pass proper retry header values to custom retry policies.

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs (hunk 18 above)
Comment (MarcinHoppe) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: @andreasohlund This means we now need to document that in v5 user can access all retry headers in their custom retry policies and in v6 they cannot. Is this what we want?

File: src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs (hunk 19 above)
Comment (MarcinHoppe) [inline src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs]: Smells like scope creep to me. Does it add much value with regards to this bug fix?

Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs]: I agree let's not add it here

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs (hunk 16 above)
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: I think we can change that later.

**Comment by MarcinHoppe** [comment]
@andreasohlund @timbussmann Is anyone of you looking at this?

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs [hunk 27]
```diff
@@ -11,14 +12,26 @@ namespace NServiceBus
...
+        public SecondLevelRetriesBehavior(SecondLevelRetryPolicy retryPolicy, string localAddress, FailureInfoStorage failureInfoStorage)
         {
             this.retryPolicy = retryPolicy;
             this.localAddress = localAddress;
+            this.failureInfoStorage = failureInfoStorage;
         }
 
         public override async Task Invoke(ITransportReceiveContext context, Func<Task> next, Func<IRoutingContext, Task> fork)
         {
+            var message = context.Message;
```
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: remove that variable

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs [hunk 28]
```diff
@@ -30,39 +43,50 @@ public SecondLevelRetriesBehavior(SecondLevelRetryPolicy retryPolicy, string loc
...
+                    new DelayDeliveryWith(delay)
+                });
 
-                    return;
-                }
+                Logger.Warn($"Second Level Retry will reschedule message '{message.MessageId}' after a delay of {delay} because of an exception:", failureInfo.Exception);
+
+                await fork(dispatchContext).ConfigureAwait(false);
+
+                failureInfoStorage.ClearFailureInfoForMessage(message.MessageId);
```
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: I think there may be conflicts with transaction rollbacks since I assume that the failureInfoStroage is non-transactional?

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs [hunk 29]
```diff
@@ -30,39 +43,50 @@ public SecondLevelRetriesBehavior(SecondLevelRetryPolicy retryPolicy, string loc
...
 
-                message.Headers.Remove(Headers.Retries);
-                Logger.WarnFormat("Giving up Second Level Retries for message '{0}'.", message.MessageId);
-                throw;
+                await context.RaiseNotification(new MessageToBeRetried(currentRetry, delay, context.Message, failureInfo.Exception)).ConfigureAwait(false);
+
+                return;
             }
+
+            message.Headers.Remove(Headers.Retries);
```
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: do we really need to remove the headers here?

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs (hunk 28 above)
Comment (andreasohlund) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: Yea, I think we have to let the LRU do its thing since we can't clear here. There is plans to have a "after transport has commited the receive op" in the future that would have been sutiable

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetries.cs [hunk 30]
```diff
@@ -19,6 +20,16 @@ internal SecondLevelRetries()
             Prerequisite(context => !context.Settings.GetOrDefault<bool>("Endpoint.SendOnly"), "Send only endpoints can't use SLR since it requires receive capabilities");
 
             Prerequisite(IsEnabledInConfig, "SLR was disabled in config");
+
+            Prerequisite(context =>
+            {
+                if (context.Settings.GetRequiredTransactionModeForReceives() == TransportTransactionMode.None)
+                {
+                    throw new Exception("Second Level Retries cannot be used in TransportTransactionMode.None. Retries have to be explicitly disabled.");
```
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetries.cs]: seems like we should also tell the user how to disable SLR?

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs (hunk 29 above)
Comment (andreasohlund) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: good catch, not needed since we now rollback

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetries.cs (hunk 15 above)
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetries.cs]: I tend to agree with @tmasternak , relying on a dependency from a different feature seems to be a brittle solution. Even if we do, this feature should at least depend on the `MoveFaultsToErrorQueue` feature to show the dependency.

File: src/NServiceBus.Core/Recoverability/Faults/StoreFaultsInErrorQueue.cs [hunk 31]
```diff
@@ -18,7 +19,12 @@ protected internal override void Setup(FeatureConfigurationContext context)
         {
             var errorQueue = ErrorQueueSettings.GetConfiguredErrorQueue(context.Settings);
             context.Settings.Get<QueueBindings>().BindSending(errorQueue);
-            context.Pipeline.Register(new MoveFaultsToErrorQueueBehavior.Registration(errorQueue, context.Settings.LocalAddress()));
+
+            var failureInfoStorage = new FailureInfoStorage(context.Settings.GetOrDefault<int?>("Recoverability.FailureInfoStorage.CacheSize") ?? 1000);
```
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/Faults/StoreFaultsInErrorQueue.cs]: we could set 1000 as a default in the feature ctor using the defaults config.

File: src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs [hunk 32]
```diff
@@ -147,6 +177,10 @@ public void AbortReceiveOperation()
                 ReceiveOperationWasAborted = true;
             }
         }
+        static FailureInfoStorage GetFailureInfoStorage()
```
Comment (timbussmann) [inline src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs]: why not just create that in `Setup`?

File: src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs [hunk 33]
```diff
@@ -16,126 +16,156 @@
...
+        FakeTransportReceiveContext CreateContext()
+        {
+            return CreateContext(CreateMessage());
+        }
+
+        FakeTransportReceiveContext CreateContext(IncomingMessage message)
+        {
+            var context = new FakeTransportReceiveContext(message);
+
+            context.Extensions.Set<IPipelineCache>(new FakePipelineCache(dispatchPipline));
```
Comment (timbussmann) [inline src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs]: the idea is to not the `Invoke(context, next, fork)` instead of setting up the pipeline cache

File: src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs [hunk 34]
```diff
@@ -16,126 +16,156 @@
...
+            var message = CreateMessage(id: "message-id", slrRetryHeader: "1");
+            var context = CreateContext(message);
 
-            var context = CreateContext("someid", 1, fakeDispatchPipeline);
+            var delay = TimeSpan.FromSeconds(5);
+            var behavior = new SecondLevelRetriesBehavior(new FakePolicy(delay), "deferral-address", GetFailureInfoStorage());
 
-            await behavior.Invoke(context, () => { throw new Exception("testex"); });
+            await behavior.Invoke(context, () => { throw new Exception("exception-message"); });
+            await behavior.Invoke(context, () => Task.FromResult(0));
```
Comment (timbussmann) [inline src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs]: I'm on the fence about these stateful tests. Wouldn't it be easier to verify/setup on single Invoke calls?

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_slr_is_on_and_transaction_mode_is_none.cs [hunk 35]
```diff
@@ -0,0 +1,63 @@
...
+{
+    using System;
+    using System.Linq;
+    using System.Threading.Tasks;
+    using AcceptanceTesting;
+    using EndpointTemplates;
+    using Features;
+    using NUnit.Framework;
+
+    public class When_slr_is_on_and_transaction_mode_is_none : NServiceBusAcceptanceTest
```
Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_slr_is_on_and_transaction_mode_is_none.cs]: nitpicking: use enabled instead of on.

Maybe shorten it to `When_slr_enabled_and_transaction_mode_none`?

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_slr_is_on_and_transaction_mode_is_none.cs [hunk 36]
```diff
@@ -0,0 +1,63 @@
...
+            try
+            {
+                await Scenario.Define<Context>()
+                    .WithEndpoint<Endpoint>(b => b.When(bus => bus.SendLocal(new Message())))
+                    .Done(c => c.MessageSentToErrorQueue)
+                    .Run();
+            }
+            catch (AggregateException ex)
+            {
+                var initializationException = ex.InnerExceptions.First();
```
Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_slr_is_on_and_transaction_mode_is_none.cs]: use `ex.InnerException`?

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_handled_by_slr.cs [hunk 37]
```diff
@@ -0,0 +1,146 @@
...
+
+        class ErrorSpy : EndpointConfigurationBuilder
+        {
+            public ErrorSpy()
+            {
+                EndpointSetup<DefaultServer>(config => config.LimitMessageProcessingConcurrencyTo(1))
+                    .CustomEndpointName(ErrorSpyQueueName);
+            }
+
+            class ErrorHandler : IHandleMessages<InitiatingMessage>, IHandleMessages<OutgoingMessage>
```
Comment (danielmarbach) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_handled_by_slr.cs]: The usage of `OutgoingMessage` confused me because we have a type in NSB with that name. Could be come up with another name?

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_handled_by_slr_using_dtc.cs [hunk 38]
```diff
@@ -0,0 +1,112 @@
...
+            {
+                public Context TestContext { get; set; }
+
+                public Task Handle(MessageToFail message, IMessageHandlerContext context)
+                {
+                    if (message.Id == TestContext.Id)
+                    {
+                        TestContext.NumberOfProcessingAttempts++;
+
+                        Transaction.Current.TransactionCompleted += CaptureTransactionStatus;
```
Comment (danielmarbach) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_handled_by_slr_using_dtc.cs]: Interesting approach. Another would have been to write a fake enlistment.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue.cs [hunk 39]
```diff
@@ -0,0 +1,168 @@
...
+            )
+            .WithEndpoint<ErrorSpy>()
+            .Done(c => c.MessageMovedToErrorQueue)
+            .Repeat(r => r.For<AllDtcTransports>())
+            .Should(c => Assert.IsFalse(c.OutgoingMessageSent, "Outgoing messages should not be sent"))
+            .Run();
+        }
+
+        [Test]
+        public async Task May_send_outgoing_messages_without_transport_transactions()
```
Comment (danielmarbach) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue.cs]: Move out into separate When class?

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue.cs [hunk 40]
```diff
@@ -0,0 +1,168 @@
...
+
+                    return Task.FromResult(0);
+                }
+            }
+
+            class OutgoingMessageHandler : IHandleMessages<OutgoingMessage>
+            {
+                public Context TestContext { get; set; }
+
+                public Task Handle(OutgoingMessage message, IMessageHandlerContext context)
```
Comment (danielmarbach) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue.cs]: Again `OutgoingMessage`

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs (hunk 28 above)
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: > I think there may be conflicts with transaction rollbacks since I assume that the failureInfoStroage is non-transactional?

@timbussmann I'm not sure I'm following.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue.cs [hunk 41]
```diff
@@ -0,0 +1,168 @@
...
+
+        class ErrorSpy : EndpointConfigurationBuilder
+        {
+            public ErrorSpy()
+            {
+                EndpointSetup<DefaultServer>(config => config.LimitMessageProcessingConcurrencyTo(1))
+                    .CustomEndpointName(ErrorSpyQueueName);
+            }
+
+            class ErrorHandler : IHandleMessages<InitiatingMessage>
```
Comment (danielmarbach) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue.cs]: In a previous test `ErrorHandler` implemented both `IHandleMessages<InitiatingMessage>` and `IHandleMessages<OutgoingMessage` I think the tests should be aligned. I'm in favour of having to classes but that is just my 2 cents.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue_using_dtc.cs [hunk 42]
```diff
@@ -0,0 +1,102 @@
...
+    using System.Collections.Generic;
+    using System.Threading.Tasks;
+    using System.Transactions;
+    using AcceptanceTesting;
+    using EndpointTemplates;
+    using Features;
+    using NUnit.Framework;
+    using ScenarioDescriptors;
+
+    public class When_message_is_moved_to_error_queue_using_dtc : NServiceBusAcceptanceTest
```
Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue_using_dtc.cs]: I think this test has a weird scoping. The Errorqueue behavior shouldn't behave differently whether it uses DTC or non-dtc transactions? (I think it even shouldn't behave differently on any transaction config, we should have a different behavior for non-transactional errorqueue handling).

Transaction handling seems to be out of scope for this test?

File: src/NServiceBus.Core.Tests/Faults/MoveFaultsToErrorQueueTests.cs [hunk 43]
```diff
@@ -12,89 +12,140 @@ namespace NServiceBus.Core.Tests
...
+            }
 
-            var context = CreateContext("someid", fakeFaultPipeline);
+            var notification = context.GetNotification<MessageFaulted>();
 
+            Assert.AreEqual("message-id", notification.Message.MessageId);
+            Assert.AreEqual("exception-message", notification.Exception.Message);
+        }
+        
+        [TestCase(TransportTransactionMode.ReceiveOnly)]
```
Comment (danielmarbach) [inline src/NServiceBus.Core.Tests/Faults/MoveFaultsToErrorQueueTests.cs]: What about `[TestCase(TransportTransactionMode.None)]`?

**Comment by timbussmann** [comment]
I think the acceptance tests have weird scopes. Let's have a call to discuss this.

File: src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/DefaultRetryPolicyTests.cs [hunk 44]
```diff
@@ -36,7 +36,7 @@ public void ShouldCapTheRetryMaxTimeTo24Hours()
             var moreThanADayAgo = now.AddHours(-24).AddTicks(-1);
             var headers = new Dictionary<string, string>
             {
-                {SecondLevelRetriesBehavior.RetriesTimestamp, DateTimeExtensions.ToWireFormattedString(moreThanADayAgo)}
+                {Headers.RetriesTimestamp, DateTimeExtensions.ToWireFormattedString(moreThanADayAgo)}
```
Comment (danielmarbach) [inline src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/DefaultRetryPolicyTests.cs]: Is this spacing correct?

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs (hunk 28 above)
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: @tmasternak commiting the transaction can fail after `ClearFailureInfoForMessage` has been called. This will result in the message being redelivered but the failure storage being empty for that message, meaning it will be retried again starting with FLR. Seems to be a tradeoff on different levels (performance, memory pressure, "number of retries consistency").

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue.cs (hunk 39 above)
Comment (MarcinHoppe) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue.cs]: What would the benefit be? This test is essentialy testing the `TransportTransactionMode.None` case missing from the test above.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_handled_by_slr.cs (hunk 37 above)
Comment (MarcinHoppe) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_handled_by_slr.cs]: Good catch. Fixed.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue.cs (hunk 41 above)
Comment (MarcinHoppe) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue.cs]: Fixed.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue.cs (hunk 40 above)
Comment (MarcinHoppe) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue.cs]: Fixed.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue_using_dtc.cs (hunk 42 above)
Comment (MarcinHoppe) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue_using_dtc.cs]: @timbussmann I agree that it should behave in the same way. What would be the value of removing this test? IMO it gives us additional safety net.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue.cs (hunk 39 above)
Comment (danielmarbach) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue.cs]: In general we try to avoid having two shoulds in the same when. But if there are strong reasons to have two in one then we leave it. According to your explanation it makes sense since it covers the leftover case from the first should.

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs (hunk 28 above)
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: @timbussmann I agree. That being said my understanding is that until we have transactional `FailureStorage` and/or extension point in transport to execute code after transaction completes there is not much we can do.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_slr_is_on_and_transaction_mode_is_none.cs (hunk 35 above)
Comment (MarcinHoppe) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_slr_is_on_and_transaction_mode_is_none.cs]: Fixed.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_slr_is_on_and_transaction_mode_is_none.cs (hunk 36 above)
Comment (MarcinHoppe) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_slr_is_on_and_transaction_mode_is_none.cs]: Fixed.

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs (hunk 29 above)
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: I think that when we run in `TransacitonMode.None` the transaction will not be rolled-back but moved to error queue in best-effort way.

File: src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs (hunk 32 above)
Comment (tmasternak) [inline src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs]: My argument are:
 * From test perspective `10` in constructor is nose
 * We reduce coupling. If constructor changes we have a better change of changing only one line instead of all usages in tests

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs (hunk 29 above)
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: @tmasternak the error behavior does remove these headers anyway: https://github.com/Particular/NServiceBus/pull/3614/files/a35bd15db4af84785fd260bbe06b76e8ee758ad0#diff-4c3990f9ae3dc5f32d6830536907820aR65

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue_using_dtc.cs (hunk 42 above)
Comment (tmasternak) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue_using_dtc.cs]: @timbussmann I think that there are two problems here.  We do want to test that no side-effects are commited when doing SLR/Errors. This includes:
   *  User code operations enlisted in `TransactionScope` - this test does that
   *  Persister operations when `TransportTransaction` is shared between transport and persister. This would be tricky to test I think and we do not have tests for that.

Comment (MarcinHoppe) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue_using_dtc.cs]: @timbussmann @tmasternak Should we handle this missing test case as a separate GitHub issue? I'd love to move towards closing this PR (and parent issue) without creating more work within the issue at hand, if possible.

Comment (tmasternak) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue_using_dtc.cs]: I'm all for leaving the second test outside of scope. By `would be tricky` I meant:
 * I think in practice only `SqlTransport` and 'NHibernate` persister can do that
 * In that case they still use `TransactionScope` but do not escalate to DTC
 * I don't think `Core` is proper place for doing that.

File: src/NServiceBus.Core.Tests/Faults/MoveFaultsToErrorQueueTests.cs (hunk 43 above)
Comment (tmasternak) [inline src/NServiceBus.Core.Tests/Faults/MoveFaultsToErrorQueueTests.cs]: The reason is that in `TransportTransaction.None` message is moved to error queue on the first call. So this test would fail in this case. Maybe what is shows is that we need a two behaviors for handling errors in different transaction modes.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue_using_dtc.cs (hunk 42 above)
Comment (MarcinHoppe) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue_using_dtc.cs]: :+1: for not doing the test and leaving this one in place.

File: src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/DefaultRetryPolicyTests.cs (hunk 44 above)
Comment (MarcinHoppe) [inline src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/DefaultRetryPolicyTests.cs]: @danielmarbach It is as correct as it was before the change, I think. What can be incorrect about spacing here?

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs (hunk 28 above)
Comment (MarcinHoppe) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: @timbussmann @tmasternak @andreasohlund Do we have consensus to leave the current behavior as is and accept the limitation?

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetries.cs (hunk 15 above)
Comment (MarcinHoppe) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetries.cs]: Added explicit dependencies.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue_using_dtc.cs (hunk 42 above)
Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue_using_dtc.cs]: > We do want to test that no side-effects are commited when doing SLR/Errors

I can see why you want to test that here based on the related bug. But I'm still not entirely convinced this is the right way to do it. In that case we have to test all the side effects for FLR, SLR and the error queue for all different transaction modes.

e.g. testing for no outgoing messages in FLR/SLR when transaction mode < MultiQueueTx is wrong. It's not always the transaction which does rollback the messages, it's the batching feature and in case something goes wrong after batching, we have outgoing messages when not using MultiQueue Transactions, that's why I hesitate to mix up these different behaviors because it makes things really confusing.

Retries don't do anything to transactions. Retries tell the transport to not consume the message. The transaction is the mechanism implementing this. Retries don't ensure other databases or outgoing messages are enlisted in transactions if possible. Retries ensure the message will be processed again on a processing failure. I see that the existing tests obviously weren't good enough to account for the wrong behavior. But if we had tested whether retries tell the transport API to not consume the message, we would have found that bug in the buggy implementation too, without testing for outgoing messages or transactions.

It's kinda a discussion between integration vs. component tests. I see that the tests make sense from an user perspective (and therefore seems a valid acceptance test). But they are also significantly harder to understand to the full level or may be misleading (see batched dispatch using single queue transactions). Personally I'leaning toward component here but that's highly subjective.

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs (hunk 28 above)
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: > until we have transactional FailureStorage and/or extension point in transport to execute code after transaction completes there is not much we can do.

not clearing seems to be something we can do?

Comment (andreasohlund) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: I'm with @timbussmann , lets not clear the storage and let the LRU handle it?

If we don't we can get into an endless loop?

Comment (MarcinHoppe) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: If we don't clear, we get into infinite loop of deferral.

File: src/NServiceBus.Core.Tests/Recoverability/FailureInfoStorageTests.cs [hunk 45]
```diff
@@ -0,0 +1,90 @@
...
+
+            storage.MarkForFirstLevelRetry(lruMessageId, ExceptionDispatchInfo.Capture(new Exception()));
+
+            for (var i = 0; i < MaxElements; ++i)
+            {
+                var messageId = Guid.NewGuid().ToString("D");
+                var exception = new Exception();
+
+                storage.MarkForFirstLevelRetry(messageId, ExceptionDispatchInfo.Capture(exception));
+                storage.MarkForFirstLevelRetry(messageId, ExceptionDispatchInfo.Capture(exception));
```
Comment (timbussmann) [inline src/NServiceBus.Core.Tests/Recoverability/FailureInfoStorageTests.cs]: why is the message marked twice in this loop?

File: src/NServiceBus.Core.Tests/Recoverability/FailureInfoStorageTests.cs [hunk 46]
```diff
@@ -0,0 +1,90 @@
...
+            Assert.NotNull(failureInfo);
+            
+            storage.ClearFailureInfoForMessage(messageId);
+
+            failureInfo = storage.GetFailureInfoForMessage(messageId);
+            Assert.AreSame(ProcessingFailureInfo.NullFailureInfo, failureInfo);
+        }
+
+        [Test]
+        public void When_recording_more_than_max_number_of_failures_should_remove_least_recently_used_entry()
```
Comment (timbussmann) [inline src/NServiceBus.Core.Tests/Recoverability/FailureInfoStorageTests.cs]: this test doesn't seem to catch the entire logic implemented in the storage? According to this test, a ring buffer would  pass this test too.

File: src/NServiceBus.Core.Tests/Recoverability/FailureInfoStorageTests.cs (hunk 45 above)
Comment (MarcinHoppe) [inline src/NServiceBus.Core.Tests/Recoverability/FailureInfoStorageTests.cs]: Good catch. This is not strictly necessary here,

File: src/NServiceBus.Core/Recoverability/FailureInfoStorage.cs [hunk 47]
```diff
@@ -0,0 +1,111 @@
...
+                {
+                    if (failureInfoPerMessage.Count == maxElements)
+                    {
+                        // We have reached the maximum allowed capacity. Remove the LRU item.
+                        var leastRecentlyUsedEntry = leastRecentlyUsedMessages.First;
+                        failureInfoPerMessage.Remove(leastRecentlyUsedEntry.Value);
+                        leastRecentlyUsedMessages.RemoveFirst();
+                    }
+
+                    var failureInfo = updateFailure(new ProcessingFailureInfo(null, 0));
```
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/FailureInfoStorage.cs]: couldn't you pass `NullFailureInfo` here?

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs (hunk 28 above)
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs]: Ah, I see. Seems to be another "best effort" limitation on retries then.

**Comment by danielmarbach** [comment]
One thing I wanted to add here is the implementation of the LRU cache. We are currently using a lot of object allocations to keep track of the least recently used items. So for each public method on the `FailureInfoStorage` we call into the update method which calls into a function delegate which returns a new instance of `ProcessingFailureInfo`. We then replace the current nodes failure info with that new instance. So that means for each retry attempt we create a new instance and garbage collect an existing one. Do we really think this is the way to go or could we come up with another (potentially smarter) behavior?

https://github.com/Particular/NServiceBus/pull/3614/files#diff-9e1e912865e1a42c5e0a4d77524b1453R40

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_handled_by_slr.cs [hunk 48]
```diff
@@ -0,0 +1,151 @@
...
+    using System.Threading.Tasks;
+    using AcceptanceTesting;
+    using EndpointTemplates;
+    using Features;
+    using NServiceBus.Config;
+    using NServiceBus.Pipeline;
+    using NUnit.Framework;
+    using ScenarioDescriptors;
+
+    public class When_message_is_deferred_by_slr : NServiceBusAcceptanceTest
```
Comment (tmasternak) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_handled_by_slr.cs]: We should change the name of the file as well. Currently it's `When_message_is_handeled_by_slr`

**Comment by weralabaj** [comment]
@timbussmann @danielmarbach If you have no further comments, could you push the button? I'll open a new PR with component tests.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue.cs [hunk 49]
```diff
@@ -0,0 +1,168 @@
+﻿namespace NServiceBus.AcceptanceTests.Recoverability.Retries
```
Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue.cs]: seems like that test should only be in the recoverability folder and not within retries?

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue_using_dtc.cs (hunk 42 above)
Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_is_moved_to_error_queue_using_dtc.cs]: note: we discussed and spiked potential component tests for the recoverability feature which would allow to test recoverability in better isolation from other pipeline features. This will be handled in a different PR.

For this PR we're ok with testing side effects of non-recoverability features to verify the correct behavior of the recoverability.

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_slr_enabled_and_transaction_mode_none.cs [hunk 50]
```diff
@@ -0,0 +1,58 @@
...
+    using System.Threading.Tasks;
+    using AcceptanceTesting;
+    using EndpointTemplates;
+    using Features;
+    using NUnit.Framework;
+
+    public class When_slr_enabled_and_transaction_mode_none : NServiceBusAcceptanceTest
+    {
+        [Test]
+        public async Task Should_throw_exception_on_endpoint_startup()
```
Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_slr_enabled_and_transaction_mode_none.cs]: I thought we're removing this from this PR again @MarcinHoppe ?

File: src/NServiceBus.Core.Tests/Faults/MoveFaultsToErrorQueueTests.cs [hunk 51]
```diff
@@ -12,89 +12,140 @@ namespace NServiceBus.Core.Tests
...
+        public async Task ShouldForwardToErrorQueueForAllExceptions(TransportTransactionMode transactionMode)
+        {
+            var behavior = CreateBehavior(transactionMode, "errors-queue");
+            var context = CreateContext("message-id");
 
-            await behavior.Invoke(context, () => { throw new Exception("testex"); });
+            await behavior.Invoke(context, () => { throw new Exception(); });
 
-            Assert.AreEqual(errorQueueAddress, fakeFaultPipeline.Destination);
+            if (transactionMode != TransportTransactionMode.None)
```
Comment (timbussmann) [inline src/NServiceBus.Core.Tests/Faults/MoveFaultsToErrorQueueTests.cs]: since the logic for `TransportTransactionMode.None` is different I'd suggest to use a dedicated test instead of hacking it into the testcases.

File: src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs [hunk 52]
```diff
@@ -16,126 +16,158 @@
...
+            public FakeTransportReceiveContext(IncomingMessage message)
             {
-                Message = new IncomingMessage(messageId, new Dictionary<string, string>
-                {
-                    {Headers.Retries, currentRetryCount.ToString()}
-                }, new MemoryStream(messageBody ?? new byte[0]));
+                Message = message;
             }
 
             public bool ReceiveOperationWasAborted { get; private set; }
```
Comment (timbussmann) [inline src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs]: I don't see any testcase testing that the receive operation was aborted. Seems pretty crucial to me (since that's essentially what caused the bug), or am I missing something?

File: src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs [hunk 53]
```diff
@@ -8,60 +9,95 @@ namespace NServiceBus
...
-                try
+                if (RunningWithTransactions)
                 {
-                    var message = context.Message;
+                    failureInfoStorage.MarkForMovingToErrorQueue(message.MessageId, ExceptionDispatchInfo.Capture(ex));
 
-                    Logger.Error($"Moving message '{message.MessageId}' to the error queue because processing failed due to an exception:", exception);
+                    context.AbortReceiveOperation();
+                }
+                else
```
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs]: Persoanlly I'd love to see this as a dedicated behavior. This would make the behavior simpler. But this is not a blocker. But any ideas whether there is anything which would stop us from doing it?

File: src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetriesBehavior.cs [hunk 54]
```diff
@@ -28,28 +29,26 @@ public FirstLevelRetriesBehavior(FlrStatusStorage storage, FirstLevelRetryPolicy
                 var messageId = context.Message.MessageId;
                 var pipelineUniqueMessageId = messageId;
 
-                var numberOfFailures = storage.GetFailuresForMessage(pipelineUniqueMessageId);
+                storage.MarkForFirstLevelRetry(pipelineUniqueMessageId, ExceptionDispatchInfo.Capture(ex));
```
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetriesBehavior.cs]: couldn't this be placed after line 40?

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetries.cs [hunk 55]
```diff
@@ -15,10 +16,21 @@ internal SecondLevelRetries()
...
 
             Prerequisite(context => !context.Settings.GetOrDefault<bool>("Endpoint.SendOnly"), "Send only endpoints can't use SLR since it requires receive capabilities");
 
             Prerequisite(IsEnabledInConfig, "SLR was disabled in config");
+
+            Prerequisite(context =>
+            {
+                if (context.Settings.GetRequiredTransactionModeForReceives() == TransportTransactionMode.None)
+                {
+                    throw new Exception("Second Level Retries (SLR) cannot be used in TransportTransactionMode.None. Disable SLR by calling EndpointConfiguration.DisableFeature<SecondLevelRetries>() method.");
```
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetries.cs]: switch to silently disable as discussed (marking comment to prevent merging)

File: src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs (hunk 52 above)
Comment (tmasternak) [inline src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs]: Added SLR test for that.

File: src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs (hunk 53 above)
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs]: There is no blocker for doing this. The argument for not splitting it was that two new behaviors would be very similar (the only difference is the `if` statement in `catch` block). 
In addition it makes it easier to discover that the behaviors are different for transactional and non-transactional mode of operation. If we had two separate classes we would probably have to put that information in the name of the class itself.

File: src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetriesBehavior.cs (hunk 54 above)
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetriesBehavior.cs]: If we did we would have to change the SLR behavior because it assumes that storage holds number of failed processing attempts and not FLRRetries. I've change the name of the method to `AddFailedProcessingAttempt` to relfect what is actually stored.

File: src/NServiceBus.Core.Tests/Faults/MoveFaultsToErrorQueueTests.cs (hunk 51 above)
Comment (tmasternak) [inline src/NServiceBus.Core.Tests/Faults/MoveFaultsToErrorQueueTests.cs]: My worry is that it would result in a lot of duplication of code. Maybe we can extract the method called `SimulateError` that would take `TransactionMode` and execute it once or twice depending on mode?

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_slr_enabled_and_transaction_mode_none.cs (hunk 50 above)
Comment (MarcinHoppe) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_slr_enabled_and_transaction_mode_none.cs]: @timbussmann I didn't want to remove it without folks responsible for v6 scope at least acknowledging the change.

File: src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs (hunk 53 above)
Comment (MarcinHoppe) [inline src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs]: We had this as separate behaviors at one point. Majority of the code was duplicated boilerplate and the if statement was still there, just moved to the feature.

File: src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetriesBehavior.cs (hunk 54 above)
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetriesBehavior.cs]: at first glance the only usage in SLR is this:
 `message.Headers[Headers.FLRetries] = (failureInfo.FailedProcessingAttempts - 1).ToString();`

When FLR doesn't handle the message, it also shoudln't mark this as a failed attempt since that seems to be outside of FLRs responsibility. FLR can be disabled, in that case the counter would have a different behavior than with enabled FLR, right?

File: src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_slr_enabled_and_transaction_mode_none.cs (hunk 50 above)
Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_slr_enabled_and_transaction_mode_none.cs]: I really think we discussed this more than enough. SLR and FLR should be aligned in handling transaction configuration. That issue is a feature request which currently does not have priority. Even if it has, this should be a different PR.

File: src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs (hunk 53 above)
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs]: as stated above, no blocker for now but I don't think code duplication is really an argument here.

Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs]: I guess that the question to ask here is: `Is code for transactional and non-transactional behavior going to change for the same reason?`. If the answer is yes than we could go with common base-class (evil) or composition but my feeling would be that it's over engineering for such a small class.

File: src/NServiceBus.Core.Tests/Recoverability/FirstLevelRetries/FirstLevelRetriesTests.cs [hunk 56]
```diff
@@ -88,20 +90,20 @@ public void ShouldClearStorageAfterGivingUp()
...
-            var storage = new FlrStatusStorage();
+            var storage = GetFailureInfoStorage();
             var behavior = CreateFlrBehavior(new FirstLevelRetryPolicy(1), storage);
 
             await behavior.Invoke(new FakeTransportReceiveContext(messageId), () => { throw new Exception("test"); });
 
-            storage.ClearAllFailures();
+            storage.ClearFailureInfoForMessage(messageId);
 
             await behavior.Invoke(new FakeTransportReceiveContext(messageId), () => { throw new Exception("test"); });
```
Comment (danielmarbach) [inline src/NServiceBus.Core.Tests/Recoverability/FirstLevelRetries/FirstLevelRetriesTests.cs]: There is no assert in this test

File: src/NServiceBus.Core.Tests/Recoverability/FirstLevelRetries/FirstLevelRetriesTests.cs [hunk 57]
```diff
@@ -123,5 +125,9 @@ public void AbortReceiveOperation()
                 ReceiveOperationWasAborted = true;
             }
         }
+        static FailureInfoStorage GetFailureInfoStorage()
```
Comment (danielmarbach) [inline src/NServiceBus.Core.Tests/Recoverability/FirstLevelRetries/FirstLevelRetriesTests.cs]: Blank line above?

File: src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/DefaultRetryPolicyTests.cs (hunk 44 above)
Comment (danielmarbach) [inline src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/DefaultRetryPolicyTests.cs]: All ok

File: src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs [hunk 58]
```diff
@@ -16,126 +16,171 @@
...
-            var fakeDispatchPipeline = new FakeDispatchPipeline();
-            var behavior = new SecondLevelRetriesBehavior(new FakePolicy(delay), "MyAddress");
+            var behavior = new SecondLevelRetriesBehavior(new FakePolicy(delay), string.Empty, failureInfoStorage);
 
-            await behavior.Invoke(CreateContext("someid", 0, fakeDispatchPipeline), () => { throw new Exception("testex"); });
+            await behavior.Invoke(context, () => { throw new Exception(); });
+            await behavior.Invoke(context, () => Task.FromResult(0) );
 
-            Assert.True(fakeDispatchPipeline.RoutingContext.Message.Headers.ContainsKey(SecondLevelRetriesBehavior.RetriesTimestamp));
+            Assert.True(dispatchPipline.MessageHeaders.ContainsKey(Headers.RetriesTimestamp));
```
Comment (danielmarbach) [inline src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs]: Is it enough to just check the existence of the key?

File: src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs [hunk 59]
```diff
@@ -16,126 +16,171 @@
...
-            var behavior = new SecondLevelRetriesBehavior(new FakePolicy(), "MyAddress");
-            var context = CreateContext("someid", 1, fakeDispatchPipeline);
+            var context = CreateContext();
+            var behavior = new SecondLevelRetriesBehavior(new FakePolicy(), string.Empty, failureInfoStorage);
 
-            Assert.That(async () => await behavior.Invoke(context, () => { throw new Exception("testex"); }), Throws.InstanceOf<Exception>());
+            await behavior.Invoke(context, () => { throw new Exception(); });
 
+            Assert.That(async () => await behavior.Invoke(context, () => Task.FromResult(0)), Throws.InstanceOf<Exception>());
             Assert.False(context.Message.Headers.ContainsKey(Headers.Retries));
```
Comment (danielmarbach) [inline src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs]: Switch to `Assert.That` with collection contains?

File: src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs [hunk 60]
```diff
@@ -16,126 +16,171 @@
...
-            var context = CreateContext("someid", 1, fakeDispatchPipeline);
+            var message = CreateMessage(slrRetryHeader: "1");
+            var context = CreateContext(message);
+            var behavior = new SecondLevelRetriesBehavior(new FakePolicy(TimeSpan.FromSeconds(5)), string.Empty, failureInfoStorage);
 
-            Assert.That(async () => await behavior.Invoke(context, () => { throw new MessageDeserializationException("testex"); }), Throws.InstanceOf<MessageDeserializationException>());
+            var behaviorInvocation = new TestDelegate(async () => await behavior.Invoke(context, () => { throw new MessageDeserializationException(string.Empty); }));
+
+            Assert.That(behaviorInvocation, Throws.InstanceOf<MessageDeserializationException>());
             Assert.False(context.Message.Headers.ContainsKey(Headers.Retries));
```
Comment (danielmarbach) [inline src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs]: Switch to Assert.That with collection contains?

File: src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs [hunk 61]
```diff
@@ -16,126 +16,171 @@
...
+            await behavior.Invoke(context, c =>
+            {
+                c.Message.Body = Encoding.UTF8.GetBytes("modified");
+                throw new Exception();
+            });
+      
+            await behavior.Invoke(context, () => Task.FromResult(0));
 
-            await behavior.Invoke(context, () => { throw new Exception("testex"); });
+            CollectionAssert.AreEqual(originalContent, context.Message.Body);
```
Comment (danielmarbach) [inline src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs]: Switch to Assert.That with collection assert?

File: src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetriesBehavior.cs [hunk 62]
```diff
@@ -28,28 +29,26 @@ public FirstLevelRetriesBehavior(FlrStatusStorage storage, FirstLevelRetryPolicy
...
                     Logger.InfoFormat("Giving up First Level Retries for message '{0}'.", messageId);
                     throw;
                 }
 
-                storage.IncrementFailuresForMessage(pipelineUniqueMessageId);
-
                 Logger.Info($"First Level Retry is going to retry message '{messageId}' because of an exception:", ex);
 
-                await context.RaiseNotification(new MessageToBeRetried(numberOfFailures, TimeSpan.Zero, context.Message, ex)).ConfigureAwait(false);
+                await context.RaiseNotification(new MessageToBeRetried(flrRetires, TimeSpan.Zero, context.Message, ex)).ConfigureAwait(false);
```
Comment (danielmarbach) [inline src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetriesBehavior.cs]: Spelling mistake `flrRetires`

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/CustomSecondLevelRetryPolicy.cs [hunk 63]
```diff
@@ -14,7 +14,7 @@ public override bool TryGetDelay(IncomingMessage message, Exception ex, int curr
         {
             delay = customRetryPolicy(message);
 
-            return delay != TimeSpan.Zero;
+            return delay != TimeSpan.MinValue;
```
Comment (danielmarbach) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/CustomSecondLevelRetryPolicy.cs]: Why this change? This is a behavior breaking change for custom policies. was this intentional?

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetries.cs (hunk 15 above)
Comment (danielmarbach) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetries.cs]: This shows that Recoverability should be one feature and not three. But let's address this another day

File: src/NServiceBus.Testing.Fakes/TimeoutMessage.cs [hunk 64]
```diff
@@ -0,0 +1,25 @@
+﻿namespace NServiceBus.Testing
+{
+    using System;
+
+    /// <summary>
+    /// Represents a message that is timed out, if not processed within a given timespan. Contains the message itself and its
+    /// associated options.
+    /// </summary>
+    /// <typeparam name="TMessage">The message type</typeparam>
+    public class TimeoutMessage<TMessage> : OutgoingMessage<TMessage, SendOptions>
```
Comment (danielmarbach) [inline src/NServiceBus.Testing.Fakes/TimeoutMessage.cs]: This is a leftover and should be deleted I think

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/CustomSecondLevelRetryPolicy.cs (hunk 63 above)
Comment (MarcinHoppe) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/CustomSecondLevelRetryPolicy.cs]: @danielmarbach This fixes a bug in v6. v5 and custom policies acceptance tests in v6 use TimeSpan.MinValue. This was discussed with @Particular/nservicebus-maintainers and we decided to piggy back the fix on this PR.

File: src/NServiceBus.Testing.Fakes/TimeoutMessage.cs (hunk 64 above)
Comment (timbussmann) [inline src/NServiceBus.Testing.Fakes/TimeoutMessage.cs]: yes, this can be removed

File: src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetriesBehavior.cs [hunk 65]
```diff
@@ -28,28 +29,26 @@ public FirstLevelRetriesBehavior(FlrStatusStorage storage, FirstLevelRetryPolicy
                 var messageId = context.Message.MessageId;
                 var pipelineUniqueMessageId = messageId;
 
-                var numberOfFailures = storage.GetFailuresForMessage(pipelineUniqueMessageId);
+                storage.RecordFailedProcessingAttempt(pipelineUniqueMessageId, ExceptionDispatchInfo.Capture(ex));
```
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetriesBehavior.cs]: you probably missed my comment since it's now shown due to your renaming. I still think this should go after line 40.
 Please have a look at this comment: https://github.com/Particular/NServiceBus/pull/3614#discussion_r58693790

File: src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs [hunk 66]
```diff
@@ -8,60 +9,95 @@ namespace NServiceBus
...
-                catch (Exception ex)
-                {
-                    criticalError.Raise("Failed to forward message to error queue", ex);
-                    throw;
-                }
+                await fork(faultContext).ConfigureAwait(false);
+
+                await context.RaiseNotification(new MessageFaulted(message, exception)).ConfigureAwait(false);
+
+                failureInfoStorage.ClearFailureInfoForMessage(message.MessageId);
```
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs]: we discussed this on FLR and you convinced me that we can't remove it there because of infinite loops. Just want to double check if we also need it here since an infinite loop isn't directly a problem? But it would cause issues if the user tries to replay his message in case the storage isn't cleared, right?

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/CustomSecondLevelRetryPolicy.cs (hunk 63 above)
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/CustomSecondLevelRetryPolicy.cs]: afaik this is the same behavior as v5

Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/CustomSecondLevelRetryPolicy.cs]: question to the task-force: the retries docs seems to correctly document MinValue already. Did you check for other usages (e.g. samples?)

**Comment by timbussmann** [comment]
needs a rebase

File: src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs (hunk 66 above)
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs]: That's correct. If the user tries to manually reply the message and it's still in in-memory failure storage it will be immediately moved to `error` queue.

File: src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetriesBehavior.cs (hunk 54 above)
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetriesBehavior.cs]: Good catch! This was a bug - if FLR was disabled than the header passed to custom SLR policy would have a wrong value:
 * I've changed the name of `FailureInfo` property to reflect the intent - now it's `FLRetries`
 * I've added test to cover this scenario
 * I've moved incrementing the counter to after the notification call

File: src/NServiceBus.Core.Tests/Recoverability/FirstLevelRetries/FirstLevelRetriesTests.cs (hunk 56 above)
Comment (tmasternak) [inline src/NServiceBus.Core.Tests/Recoverability/FirstLevelRetries/FirstLevelRetriesTests.cs]: Done.

File: src/NServiceBus.Core.Tests/Recoverability/FirstLevelRetries/FirstLevelRetriesTests.cs (hunk 57 above)
Comment (tmasternak) [inline src/NServiceBus.Core.Tests/Recoverability/FirstLevelRetries/FirstLevelRetriesTests.cs]: Done

File: src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs (hunk 58 above)
Comment (tmasternak) [inline src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs]: I've added if the value is properly formatted.

File: src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs (hunk 60 above)
Comment (tmasternak) [inline src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs]: Switched to `Assert.That`

File: src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs (hunk 61 above)
Comment (tmasternak) [inline src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs]: Can you be more specific. I'm not sure I follow.

File: src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetriesBehavior.cs (hunk 62 above)
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetriesBehavior.cs]: Done.

File: src/NServiceBus.Testing.Fakes/TimeoutMessage.cs (hunk 64 above)
Comment (tmasternak) [inline src/NServiceBus.Testing.Fakes/TimeoutMessage.cs]: Done

File: src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetriesBehavior.cs (hunk 65 above)
Comment (tmasternak) [inline src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetriesBehavior.cs]: Moved after notification is fired.

File: src/NServiceBus.Core/Recoverability/SecondLevelRetries/CustomSecondLevelRetryPolicy.cs (hunk 63 above)
Comment (weralabaj) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/CustomSecondLevelRetryPolicy.cs]: @timbussmann I've checked, I didn't find any other usages in the docs repo.

Comment (danielmarbach) [inline src/NServiceBus.Core/Recoverability/SecondLevelRetries/CustomSecondLevelRetryPolicy.cs]: Ok I didn't know that. Sorry that was either never told to me or I forgot it (which is probably more likely)

**Comment by weralabaj** [comment]
@timbussmann @danielmarbach back to you

File: src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetriesBehavior.cs [hunk 67]
```diff
@@ -28,28 +29,26 @@ public FirstLevelRetriesBehavior(FlrStatusStorage storage, FirstLevelRetryPolicy
                 var messageId = context.Message.MessageId;
                 var pipelineUniqueMessageId = messageId;
 
-                var numberOfFailures = storage.GetFailuresForMessage(pipelineUniqueMessageId);
+                var fltRetries = storage.GetFailureInfoForMessage(pipelineUniqueMessageId).FLRetries;
```
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetriesBehavior.cs]: should that be `flrRetries`?

File: src/NServiceBus.Core/Recoverability/ProcessingFailureInfo.cs [hunk 68]
```diff
@@ -0,0 +1,25 @@
...
+    {
+        public ProcessingFailureInfo(ExceptionDispatchInfo exceptionDispatchInfo, int flRetries, bool moveToErrorQueue = false, bool deferForSecondLevelRetry = false)
+        {
+            FLRetries = flRetries;
+            ExceptionDispatchInfo = exceptionDispatchInfo;
+            MoveToErrorQueue = moveToErrorQueue;
+            DeferForSecondLevelRetry = deferForSecondLevelRetry;
+        }
+        
+        public int FLRetries { get; }
```
Comment (timbussmann) [inline src/NServiceBus.Core/Recoverability/ProcessingFailureInfo.cs]: I think it would be better to not shortcut the name (same for the ctor argument)
