### PR TITLE
Defer TransportInfrastructure access

### LINKED ISSUE #6961: Premature ITransportAddressResolver access corrupts service
#### Description

When using the generic host, it is possible to resolve `ITransportAddressResolver` before the endpoint has been started. A potential scenario is a hosted service that is trying to use the TransactionalSession ([which internally uses the `ITransportAddressResolver`](https://github.com/Particular/NServiceBus.TransactionalSession/blob/a136b6fd6313c8f01d395e5c8e5ab2f4ff4dd0c7/src/NServiceBus.TransactionalSession/TransactionalSession.cs#L42)).

Resolving the `ITransportAddressResolver` will produce an instance which uses the `transportSeam.TransportInfrastructure` property which is still null, causing it to throw an NRE once an attempt to translate a transport address is made. Since the service is registered as a singleton, all users of the singleton will receive the invalid instance and thus run into an NRE on any call to the address resolver.

#### Expected behavior

The endpoint should be able to start successfully.

Additionally, it would be nicer if the code that tries to access the `ITransportAddressResolver` prematurely will receive an exception, warning about the startup order rather than a corrupted instance which will throw NRE's on usage.

#### Actual behavior

The endpoint fails to start with an exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.TransportAddressResolver.ToTransportAddress(QueueAddress queueAddress) in /_/src/NServiceBus.Core/Transports/TransportAddressResolver.cs:line 14
   at NServiceBus.TransactionalSession.TransactionalSession.<>c.<Setup>b__1_2(IServiceProvider sp) in /_/src/NServiceBus.TransactionalSession/TransactionalSession.cs:line 74
   at NServiceBus.Pipeline.PipelineSettings.<>c__DisplayClass11_0`1.<Register>b__0(IServiceProvider b) in /_/src/NServiceBus.Core/Pipeline/PipelineSettings.cs:line 180
   at NServiceBus.Pipeline.RegisterStep.CreateBehavior(IServiceProvider defaultBuilder) in /_/src/NServiceBus.Core/Pipeline/RegisterStep.cs:line 131
   at NServiceBus.Pipeline`1.<>c__DisplayClass0_0.<.ctor>b__0(RegisterStep r) in /_/src/NServiceBus.Core/Pipeline/Pipeline.cs:line 27
   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at NServiceBus.Pipeline`1..ctor(IServiceProvider builder, PipelineModifications pipelineModifications) in /_/src/NServiceBus.Core/Pipeline/Pipeline.cs:line 26
   at NServiceBus.PipelineComponent.CreatePipeline[T](IServiceProvider builder) in /_/src/NServiceBus.Core/Pipeline/PipelineComponent.cs:line 32
   at NServiceBus.ReceiveComponent.Initialize(IServiceProvider builder, RecoverabilityComponent recoverabilityComponent, MessageOperations messageOperations, PipelineComponent pipelineComponent, IPipelineCache pipelineCache, TransportInfrastructure transportInfrastructure, ConsecutiveFailuresConfiguration consecutiveFailuresConfiguration, CancellationToken cancellationToken) in /_/src/NServiceBus.Core/Receiving/ReceiveComponent.cs:line 157
   at NServiceBus.StartableEndpoint.Setup(CancellationToken cancellationToken) in /_/src/NServiceBus.Core/StartableEndpoint.cs:line 50
   at NServiceBus.ExternallyManagedContainerHost.Start(IServiceProvider externalBuilder, CancellationToken cancellationToken) in /_/src/NServiceBus.Core/Hosting/ExternallyManagedContainerHost.cs:line 41
   at NServiceBus.Extensions.Hosting.NServiceBusHostedService.StartAsync(CancellationToken cancellationToken) in /_/src/NServiceBus.Extensions.Hosting/NServiceBusHostedService.cs:line 30
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
```

#### Versions

Please list the version of the relevant packages or applications in which the bug exists.        

Core v8 + TransactionalSession for SQLP

### Steps to reproduce

1. Create a hosted service which accesses `ITransportAddressResolver`
2. Register the hosted service before calling `UseNServiceBus` on the generic host setup
3. Start the host

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mikeminutillo**
- Fixes: #6961 

Defers the access of transport infrastructure to when an address needs to be resolved.

When an `IHostedService` has a (direct or indirect) dependency on `ITransportAddressResolver` it may be resolved from the container before the transport has been initialized. This leaves the configure Transport Address Resolver in an invalid state.

This happens because all of the `IHostedService` instances are resolved at once but then started sequentially. Even if the hosted services are registered in the right order, the `ITransportAddressResolver` will be in an invalid state forever.

This PR defers access to the transport infratsructure to when an address is resolved. As long as this access occurs after the endpoint has been started, everything will work.

```cs
var serviceCollection = new ServiceCollection();

var startable = EndpointWithExternallyManagedContainer.Create(endpointConfig, serviceCollection);

var transportAddress = new QueueAddress("SomeAddress");

using var serviceProvider = serviceCollection.BuildServiceProvider();

// Does not throw. Correctly as the transport address resolver is registered
var transportAddressResolver = serviceProvider.GetRequiredService<ITransportAddressResolver>();

// Throws, as the transport has not been started
//Console.WriteLine(transportAddressResolver.ToTransportAddress(transportAddress));

var endpoint = await startable.Start(serviceProvider);

// Should not throw, but does
Console.WriteLine(transportAddressResolver.ToTransportAddress(transportAddress));

```

### CODE REVIEW

**Comment by mikeminutillo** [comment]
It will still throw a Null Reference Exception if the transport address resolver is used before the endpoint is started. Perhaps I should add another test for that and improve the exception message.

**Comment by andreasohlund** [comment]
>It will still throw a Null Reference Exception if the transport address resolver is used before the endpoint is started. Perhaps I should add another test for that and improve the exception message.

Yea, that sounds good!

File: src/NServiceBus.AcceptanceTests/Core/DependencyInjection/When_resolving_before_endpoint_is_started.cs [hunk 1]
```diff
@@ -43,6 +44,50 @@ public async Task Should_be_able_to_use_transport_adddress_resolver_after_the_en
...
+                {
+                    var serviceProvider = serviceCollection.BuildServiceProvider();
+
+                    // HINT: Resolve before start
+                    var transportAddressResolver = serviceProvider.GetRequiredService<ITransportAddressResolver>();
+
+                    try
+                    {
+                        // HINT: Call before start
+                        transportAddressResolver.ToTransportAddress(new QueueAddress("SomeAddress"));
```
Comment (andreasohlund) [inline src/NServiceBus.AcceptanceTests/Core/DependencyInjection/When_resolving_before_endpoint_is_started.cs:67]: Is there a reason to not use `Assert.Throws<>` here?

Comment (mikeminutillo) [reply src/NServiceBus.AcceptanceTests/Core/DependencyInjection/When_resolving_before_endpoint_is_started.cs:67]: I wonder if it's worth having some different abstraction to test endpoint configuration. i.e. I give you an endpoint builder, and a context, and then you give me back a fully configured endpoint configuration.

Comment (andreasohlund) [reply src/NServiceBus.AcceptanceTests/Core/DependencyInjection/When_resolving_before_endpoint_is_started.cs:67]: It wouldn't bubble but you can set the ex != null as a done statement?

Comment (mikeminutillo) [reply src/NServiceBus.AcceptanceTests/Core/DependencyInjection/When_resolving_before_endpoint_is_started.cs]: Done

**Review by andreasohlund — APPROVED** [review]
Made some minor tweaks, please take a look
