### PR TITLE
Fix wire compatibility for v6

### LINKED ISSUE #3583: Missing Version and TimeSent headers breaks wire compatibility with v6 for subscription messages
Here are the current headers being set:
```xml
<?xml version="1.0"?>
<ArrayOfHeaderInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<HeaderInfo>
		<Key>NServiceBus.ControlMessage</Key>
		<Value>True</Value>
	</HeaderInfo>
	<HeaderInfo>
		<Key>NServiceBus.MessageIntent</Key>
		<Value>Subscribe</Value>
	</HeaderInfo>
	<HeaderInfo>
		<Key>SubscriptionMessageType</Key>
		<Value>Version_3_3.Messages.MyEvent, Version_3_3.Messages, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null</Value>
	</HeaderInfo>
	<HeaderInfo>
		<Key>NServiceBus.ReplyToAddress</Key>
		<Value>WireCompatVersion_6_0@JOHNPC2</Value>
	</HeaderInfo>
	<HeaderInfo>
		<Key>NServiceBus.SubscriberAddress</Key>
		<Value>WireCompatVersion_6_0@JOHNPC2</Value>
	</HeaderInfo>
	<HeaderInfo>
		<Key>NServiceBus.SubscriberEndpoint</Key>
		<Value>WireCompatVersion_6_0</Value>
	</HeaderInfo>
	<HeaderInfo>
		<Key>CorrId</Key>
		<Value />
	</HeaderInfo>
</ArrayOfHeaderInfo>
```

### PR DESCRIPTION
**Pull request by johnsimons**
Theses issues were uncovered by #3573:

1. [x] Stop deserializing control messages  
Control messages are still being received from early versions of NServiceBus, eg v3.3
1. [x] Add missing Version and TimeSent headers to subscribe and unsubscribe messages
1. [x] Attempt to assign incoming message id as correlation id

fixes #3583

### CODE REVIEW

**Comment by johnsimons** [comment]
@Particular/nservicebus-maintainers I think this is the fix ? Please let me know if this is the way to go, and I will add some testing to it.

**Comment by danielmarbach** [comment]
In previous versions we still continued the pipeline, see https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Unicast/Messages/DeserializeLogicalMessagesBehavior.cs#L32

**Comment by danielmarbach** [comment]
Furthermore why aren't they caught by this check?

https://github.com/Particular/NServiceBus/blob/Dont_deserialize_control_messages/src/NServiceBus.Core/Pipeline/Incoming/DeserializeLogicalMessagesConnector.cs#L59

**Comment by johnsimons** [comment]
> Furthermore why aren't they caught by this check?

No idea, but here are the errors I am getting https://github.com/Particular/NServiceBus/issues/3573#issuecomment-195178593
I am not sure if there is much point in continuing the pipeline because there is really no `IncomingLogicalMessage`, but I leave that up to u

**Comment by johnsimons** [comment]
Ok I figure out why the `if (physicalMessage.Body == null || physicalMessage.Body.Length == 0)` does not stop this.
It seems in v3.3 control messages also included a body!
Here it is:
```xml
<?xml version="1.0"?>
<Messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://tempuri.net/NServiceBus.Unicast.Transport">
	<CompletionMessage>
		<ErrorCode>5</ErrorCode>
	</CompletionMessage>
</Messages>
```

**Comment by bording** [comment]
If 3.3 is no longer supported, is this even something we need to care about?

**Comment by johnsimons** [comment]
> In previous versions we still continued the pipeline

@danielmarbach we did continue the pipeline, but it seems right now we don't, not sure what implications this have ?

**Comment by johnsimons** [comment]
> If 3.3 is no longer supported, is this even something we need to care about?

I believe so, even though support has expired we should help users migrate out of it.

**Comment by johnsimons** [comment]
@danielmarbach I believe this one is done.
The pipeline stops when a messages is a control message or there is no body, I haven't changed that.

**Comment by johnsimons** [comment]
Found more issues, hold on the review

**Comment by danielmarbach** [comment]
@johnsimons do you want to remove [WIP] then?

**Comment by danielmarbach** [comment]
Sorry just saw [the other comment](https://github.com/Particular/NServiceBus/pull/3576#issuecomment-196151991).

**Comment by johnsimons** [comment]
@danielmarbach all it's left is to add a test for the last point (Attempt to assign incoming message id as correlation id), do u want to take over from here ?
I'm finishing for today.
With these fixes the EndToEnd tests pass for v6 wire compat with v3.3

**Comment by danielmarbach** [comment]
Assign it to me. I have a few other things on my plate today but I see what
I can do.

**Comment by johnsimons** [comment]
@Particular/nservicebus-maintainers this one is ready to merge, thank you.

File: src/NServiceBus.AcceptanceTests/Correlation/When_repling_to_received_message_without_correlationid.cs [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+                    context.CorrelationIdReceived = c.MessageHeaders[Headers.CorrelationId];
+                    context.GotResponse = true;
+
+                    return Task.FromResult(0);
+                }
+
+                readonly Context context;
+            }
+
+            class RemoveCorrelationId : IMutateIncomingTransportMessages
```
Comment (danielmarbach) [inline src/NServiceBus.AcceptanceTests/Correlation/When_repling_to_received_message_without_correlationid.cs]: Is this really necessary. Based on the test you are not assigning the correlation id to the test context before you reply. So just be looking at the test this mutator would not be needed

File: src/NServiceBus.AcceptanceTests/Correlation/When_repling_to_received_message_without_correlationid.cs [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+                        context.Headers.Remove(Headers.CorrelationId);
+                    }
+
+                    return Task.FromResult(0);
+                }
+            }
+        }
+
+
+        [Serializable]
```
Comment (danielmarbach) [inline src/NServiceBus.AcceptanceTests/Correlation/When_repling_to_received_message_without_correlationid.cs]: @Particular/nservicebus-maintainers do we want to keep the `[Serializable]`?

File: src/NServiceBus.Core/Pipeline/Incoming/DeserializeLogicalMessagesConnector.cs [hunk 3]
```diff
@@ -31,7 +31,12 @@ public DeserializeLogicalMessagesConnector(MessageDeserializerResolver deseriali
             }
         }
 
-        List<LogicalMessage> ExtractWithExceptionHandling(IncomingMessage message)
+        static bool IsControlMessage(IncomingMessage incomingMessage)
+        {
+            return incomingMessage.Headers.ContainsKey(Headers.ControlMessageHeader) && incomingMessage.Headers[Headers.ControlMessageHeader] == true.ToString();
```
Comment (danielmarbach) [inline src/NServiceBus.Core/Pipeline/Incoming/DeserializeLogicalMessagesConnector.cs]: Just verified again that `true.ToString()` is equivalent to `Boolean.TrueString`. It uses the literals internally and ignores any culture specific settings. This is really confusing and always trips me over

http://referencesource.microsoft.com/#mscorlib/system/boolean.cs,91

File: src/NServiceBus.AcceptanceTests/Correlation/When_repling_to_received_message_without_correlationid.cs [hunk 4]
```diff
@@ -0,0 +1,96 @@
+﻿namespace NServiceBus.AcceptanceTests.Correlation
+{
+    using System;
+    using System.Threading.Tasks;
+    using AcceptanceTesting;
+    using EndpointTemplates;
+    using MessageMutator;
+    using NUnit.Framework;
+
+    public class When_repling_to_received_message_without_correlationid : NServiceBusAcceptanceTest
```
Comment (danielmarbach) [inline src/NServiceBus.AcceptanceTests/Correlation/When_repling_to_received_message_without_correlationid.cs]: Spelling in `When_repling...`

File: src/NServiceBus.Core/Pipeline/Incoming/DeserializeLogicalMessagesConnector.cs [hunk 5]
```diff
@@ -99,8 +112,7 @@ List<LogicalMessage> Extract(IncomingMessage physicalMessage)
             using (var stream = new MemoryStream(physicalMessage.Body))
             {
                 return messageSerializer.Deserialize(stream, messageTypes)
-                    .Select(x => logicalMessageFactory.Create(x.GetType(), x))
-                    .ToList();
+                    .Select(x => logicalMessageFactory.Create(x.GetType(), x));
```
Comment (danielmarbach) [inline src/NServiceBus.Core/Pipeline/Incoming/DeserializeLogicalMessagesConnector.cs]: Is there any impact here since we now lazy evaluate the enumerable?

File: src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscribeTerminator.cs [hunk 6]
```diff
@@ -39,9 +39,10 @@ public MessageDrivenSubscribeTerminator(SubscriptionRouter subscriptionRouter, s
                 subscriptionMessage.Headers[Headers.ReplyToAddress] = subscriberAddress;
                 subscriptionMessage.Headers[Headers.SubscriberTransportAddress] = subscriberAddress;
                 subscriptionMessage.Headers[Headers.SubscriberEndpoint] = subscriberEndpoint.ToString();
-                var address = publisherAddress;
+                subscriptionMessage.Headers[Headers.TimeSent] = DateTimeExtensions.ToWireFormattedString(DateTime.UtcNow);
```
Comment (danielmarbach) [inline src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscribeTerminator.cs]: I wonder if it would make sense to have some kind of extension method which sets the standard headers.

File: src/NServiceBus.Msmq.AcceptanceTests/When_receiving_control_message_with_body.cs [hunk 7]
```diff
@@ -0,0 +1,106 @@
...
+                public AssertBehavior(Context context)
+                {
+                    this.context = context;
+                }
+
+                public override async Task Invoke(IIncomingPhysicalMessageContext c, Func<Task> next)
+                {
+                    try
+                    {
+                        await next();
```
Comment (danielmarbach) [inline src/NServiceBus.Msmq.AcceptanceTests/When_receiving_control_message_with_body.cs]: Not really important here but I'd add a `ConfigureAwait(false)`

**Comment by danielmarbach** [comment]
@Particular/nservicebus-maintainers can someone else also chime in here?

File: src/NServiceBus.AcceptanceTests/Correlation/When_repling_to_received_message_without_correlationid.cs (hunk 2 above)
Comment (andreasohlund) [inline src/NServiceBus.AcceptanceTests/Correlation/When_repling_to_received_message_without_correlationid.cs]: not needed anymore

File: src/NServiceBus.AcceptanceTests/Correlation/When_repling_to_received_message_without_correlationid.cs [hunk 8]
```diff
@@ -0,0 +1,96 @@
...
+            }
+        }
+
+
+        [Serializable]
+        public class MyRequest : IMessage
+        {
+        }
+
+        [Serializable]
```
Comment (andreasohlund) [inline src/NServiceBus.AcceptanceTests/Correlation/When_repling_to_received_message_without_correlationid.cs]: Remove this as well

File: src/NServiceBus.Core/Pipeline/Incoming/DeserializeLogicalMessagesConnector.cs (hunk 5 above)
Comment (andreasohlund) [inline src/NServiceBus.Core/Pipeline/Incoming/DeserializeLogicalMessagesConnector.cs]: Could the enumeration access the stream after it has been disposed?

File: src/NServiceBus.AcceptanceTests/Correlation/When_repling_to_received_message_without_correlationid.cs (hunk 1 above)
Comment (johnsimons) [inline src/NServiceBus.AcceptanceTests/Correlation/When_repling_to_received_message_without_correlationid.cs]: Unfortunately it does, I tried without it and no love

File: src/NServiceBus.Core/Pipeline/Incoming/DeserializeLogicalMessagesConnector.cs (hunk 5 above)
Comment (johnsimons) [inline src/NServiceBus.Core/Pipeline/Incoming/DeserializeLogicalMessagesConnector.cs]: It works

**Comment by johnsimons** [comment]
@danielmarbach all actionable code review concerns addressed, happy merging :wink:

**Comment by timbussmann** [comment]
(removing labels since they are present on the linked issues)
