### PR TITLE
Scope UoW should handle default tx mode to be used

### LINKED ISSUE #3847: KeyNotFoundException when using UnitOfWork().WrapHandlersInATransactionScope()
When using UnitOfWork().WrapHandlersInATransactionScope() the core throws a KeyNotFoundException with message 'The given key (NServiceBus.TransportTransactionMode) was not present in the dictionary'

setting transportConfiguration.Transactions(TransportTransactionMode.SendsAtomicWithReceive) solved the problem for me, but the exception message could be clearer

### PR DESCRIPTION
**Pull request by andreasohlund**
Fixes #3847

### CODE REVIEW

**Comment by andreasohlund** [comment]
@Particular/nservicebus-maintainers please review

File: src/NServiceBus.AcceptanceTests/UnitOfWork/TransactionScope/When_used_with_default_transaction_mode.cs [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+
+    public class When_used_with_default_transaction_mode : NServiceBusAcceptanceTest
+    {
+        [Test]
+        public async Task Should_work()
+        {
+            var context = await Scenario.Define<Context>()
+                 .WithEndpoint<ScopeEndpoint>(b => b.CustomConfig(c =>
+                 {
+                     c.GetSettings().Set("FakeTransport.SupportedTransactionMode", TransportTransactionMode.ReceiveOnly);
```
Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/UnitOfWork/TransactionScope/When_used_with_default_transaction_mode.cs]: why is that needed? can't we just change the transaction level on the transport configuration?

Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/UnitOfWork/TransactionScope/When_used_with_default_transaction_mode.cs]: nevermind, we're testing to not use the explicit transaction config. Should we also have a test which verifies the exception if the default mode is already using `TransactionScope`?

Comment (andreasohlund) [inline src/NServiceBus.AcceptanceTests/UnitOfWork/TransactionScope/When_used_with_default_transaction_mode.cs]: Isn't that the same test as When_transactionscope_enabled.cs ?

Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/UnitOfWork/TransactionScope/When_used_with_default_transaction_mode.cs]: @andreasohlund do you mean `When_used_with_transport_scopes`? it would be kind of the same test, didn't check whether there is something comparable.

I think this would probably better suited as an unit test since the only difference here is that we're not using the `Transactions` settings but fallback to the default transport settings?

Comment (andreasohlund) [inline src/NServiceBus.AcceptanceTests/UnitOfWork/TransactionScope/When_used_with_default_transaction_mode.cs]: Sorry, yes I meant `When_used_with_transport_scopes`.

I tried a unit test first but testing the feature setup methods are tricky (so much stuff to setup, I know that @danielmarbach have propose that we invest some time to create a feature test harness)

Comment (timbussmann) [inline src/NServiceBus.AcceptanceTests/UnitOfWork/TransactionScope/When_used_with_default_transaction_mode.cs]: @andreasohlund we should probably raise an issue, since there are also users who would like to test their feature setups (e.g. maybe provide a `TestableFeatureSetupContext`)
